### PR TITLE
Versioned off at v1.1

### PR DESCRIPTION
**Pull request by vicng**
This change is [Reviewable](https://reviewable.io/reviews/google/blockly-ios/430)

### CODE REVIEW

**Comment by vicng** [comment]
+@corydcode +@roboerikg 

---

Review status: 0 of 5 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/google/blockly-ios/430#-:-KpcLdOaDdVDUtll7ZOy:b4ivu6b)*

**Comment by vicng** [comment]
I also updated the README to use an animated gif instead of a static image. You can preview what it looks like by going to github and switching the branch to "vn-v1.1".

---

Review status: 0 of 5 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/google/blockly-ios/430#-:-KpcLw8UK8YEarP4xfHc:b-lc0uhw)*

**Comment by CoryDCode** [comment]
:lgtm:

---

Review status: 0 of 5 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/google/blockly-ios/430#-:-KppZa6X0Iqe6_5NqMZM:bnfp4nl)*

**Comment by vicng** [comment]
I just noticed the README has some older text -- can you review again?

---

Review status: 0 of 5 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/google/blockly-ios/430#-:-KpqTQMVm2v20r2mqDUD:bie0xim)*

**Comment by RoboErikG** [comment]
:lgtm:

---

Review status: 0 of 5 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/google/blockly-ios/430#-:-KpqmFsJrVUbn1UFRMiO:bnfp4nl)*

**Pull request merged**
