### PR TITLE
- Added code generation support for procedure blocks

### PR DESCRIPTION
**Pull request by vicng**
This change is [Reviewable](https://reviewable.io/reviews/google/blockly-ios/309)

### CODE REVIEW

**Comment by vicng** [comment]
+@corydcode 



---

Review status: 0 of 2 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/google/blockly-ios/309#-:-KbwJIYQENENnyar_Gui:b-hjazp3)*

**Comment by RoboErikG** [comment]
:lgtm:

---

Review status: 0 of 2 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/google/blockly-ios/309#-:-KbzmRsJQn280y5FJ-Tw:bnfp4nl)*

**Comment by CoryDCode** [comment]
:lgtm:

---

Review status: 0 of 2 files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

*[Samples/BlocklySample/Resources/Turtle/toolbox.xml, line 174 at r1](https://reviewable.io:443/reviews/google/blockly-ios/309#-Kc-4hB7TuI-yTe77tMj:-Kc-4hB7TuI-yTe77tMk:b5uv7ee) ([raw file](https://github.com/google/blockly-ios/blob/79386ff3d9bc9175302d45b2cd49f408205c218e/Samples/BlocklySample/Resources/Turtle/toolbox.xml#L174)):*
> ```XML
>     </category>
>     <category name="Variables" colour="330" custom="VARIABLE">
>     </category>
> ```

Oh, can you remove this tag and just end the category with / instead?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/google/blockly-ios/309#-:-Kc-4r-xmZxqJWll_Xf2:bnfp4nl)*

**Comment by vicng** [comment]
Review status: 0 of 2 files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

*[Samples/BlocklySample/Resources/Turtle/toolbox.xml, line 174 at r1](https://reviewable.io:443/reviews/google/blockly-ios/309#-Kc-4hB7TuI-yTe77tMj:-Kc-hA0xx28RSpQYzUT_:b-896fix) ([raw file](https://github.com/google/blockly-ios/blob/79386ff3d9bc9175302d45b2cd49f408205c218e/Samples/BlocklySample/Resources/Turtle/toolbox.xml#L174)):*
<details><summary><i>Previously, CoryDCode wrote…</i></summary><blockquote>

Oh, can you remove this tag and just end the category with / instead?
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/google/blockly-ios/309)*

**Pull request merged**
