### PR TITLE
- Adds a fresh coat of paint to the UI, incorporating Material Design…

### PR DESCRIPTION
**Pull request by vicng**
… colors

- UI tweaking for all fields
- Updates popovers to open more consistently between fields and mutators
- Allows for more style configurability, by adding more keys to LayoutConfig and changing some members to be public
- Fixes block highlighting so the block highlight stroke isn't covered by child blocks
- Cleans up sample code's style/data

---
This change is [Reviewable](https://reviewable.io/reviews/google/blockly-ios/423)

### CODE REVIEW

**Comment by vicng** [comment]
+@corydcode +@roboerikg 



---

Review status: 0 of 36 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/google/blockly-ios/423#-:-Kov41MjMsM_Bj2UGhFg:b2fqe04)*

**Comment by RoboErikG** [comment]
Changes look good (a few nits) and I like the set of colors in the screenshot. Were you still going to send out a few different color pallets for comparison? :lgtm_strong: 

---

Review status: 0 of 36 files reviewed at latest revision, 5 unresolved discussions.

---

*[Samples/BlocklySample/BlocklySample/Resources/Non-Localized/AllFieldsDemo/custom_field_blocks.json, line 39 at r1](https://reviewable.io:443/reviews/google/blockly-ios/423#-KoxrCeMHR5aJGede2bE:-KoxrCeNZDBI_40JVB1a:b-6u4dv4) ([raw file](https://github.com/google/blockly-ios/blob/f46a32ee0cf8745cbcbdd5193d1c4436322ad7ef/Samples/BlocklySample/BlocklySample/Resources/Non-Localized/AllFieldsDemo/custom_field_blocks.json#L39)):*
> ```JSON
>     ],
>     "output": null,
>     "colour": "#EF6C00"
> ```

TODO in another CL, replace these colors with %{msg_references} so you can change them all at once. Web  has these defined on most of the blocks.

---

*[Samples/BlocklySample/BlocklySample/Resources/Non-Localized/Turtle/turtle_blocks.json, line 45 at r1](https://reviewable.io:443/reviews/google/blockly-ios/423#-Koxrr8ezLHKScJBG8EY:-Koxrr8ezLHKScJBG8EZ:bk2ozwm) ([raw file](https://github.com/google/blockly-ios/blob/f46a32ee0cf8745cbcbdd5193d1c4436322ad7ef/Samples/BlocklySample/BlocklySample/Resources/Non-Localized/Turtle/turtle_blocks.json#L45)):*
> ```JSON
>     "previousStatement": null,
>     "nextStatement": null,
>     "colour": "#009688",
> ```

ditto on making these %{refs} in a followup cl.

---

*[Sources/Layout/Default/DefaultLayoutConfig.swift, line 113 at r1](https://reviewable.io:443/reviews/google/blockly-ios/423#-Koxss3BGPLzB3rQDe3h:-Koxss3BGPLzB3rQDe3i:b-k3m9wa) ([raw file](https://github.com/google/blockly-ios/blob/f46a32ee0cf8745cbcbdd5193d1c4436322ad7ef/Sources/Layout/Default/DefaultLayoutConfig.swift#L113)):*
> ```Swift
>   public static let InlineConnectorMinimumSize = LayoutConfig.newPropertyKey()
> 
>   /// [`Unit`] Horizontal padding around inline connector. For inline connector rendering, this value
> ```

nit line length

---

*[Sources/UI/View Controllers/WorkbenchViewController.swift, line 271 at r1](https://reviewable.io:443/reviews/google/blockly-ios/423#-KoxtXiqVgyAFrKRfHcJ:-KoxtXiqVgyAFrKRfHcK:b-f8jr44) ([raw file](https://github.com/google/blockly-ios/blob/f46a32ee0cf8745cbcbdd5193d1c4436322ad7ef/Sources/UI/View Controllers/WorkbenchViewController.swift#L271)):*
> ```Swift
>   fileprivate let _dragger = Dragger()
>   /// Controller for listing the toolbox categories
>   open fileprivate(set) lazy var toolboxCategoryListViewController: ToolboxCategoryListViewController = {
> ```

nit line length here and below.

---

*[Sources/UI/Views/MutatorProcedureDefinitionView.swift, line 89 at r1](https://reviewable.io:443/reviews/google/blockly-ios/423#-KoxumZVT1f2vocALeF_:-KoxumZVT1f2vocALeFa:b-n0jdrs) ([raw file](https://github.com/google/blockly-ios/blob/f46a32ee0cf8745cbcbdd5193d1c4436322ad7ef/Sources/UI/Views/MutatorProcedureDefinitionView.swift#L89)):*
> ```Swift
>       self.popoverButton.tintColor =
>         layout.config.color(for: DefaultLayoutConfig.MutatorSettingsButtonColor)
>         
> ```

nit ws

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/google/blockly-ios/423#-:-KoxvPswax0EKHxbW7N8:b-j0eb3r)*

**Comment by CoryDCode** [comment]
:lgtm: Woof. That was a lot of code.

---

Review status: 0 of 36 files reviewed at latest revision, 5 unresolved discussions, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/google/blockly-ios/423#-:-Kp1O8TsKF3G3Qv8ncOi:bmc0ddy)*

**Comment by vicng** [comment]
I'll have a designer friend take a quick look to see if the colours are ok. I'll do a follow up CL if needed.

---

Review status: 0 of 36 files reviewed at latest revision, 5 unresolved discussions, all commit checks successful.

---

*[Samples/BlocklySample/BlocklySample/Resources/Non-Localized/AllFieldsDemo/custom_field_blocks.json, line 39 at r1](https://reviewable.io:443/reviews/google/blockly-ios/423#-KoxrCeMHR5aJGede2bE:-Kp1uq34mpVSecJkvpvh:bb0bt9x) ([raw file](https://github.com/google/blockly-ios/blob/f46a32ee0cf8745cbcbdd5193d1c4436322ad7ef/Samples/BlocklySample/BlocklySample/Resources/Non-Localized/AllFieldsDemo/custom_field_blocks.json#L39)):*
<details><summary><i>Previously, RoboErikG wrote…</i></summary><blockquote>

TODO in another CL, replace these colors with %{msg_references} so you can change them all at once. Web  has these defined on most of the blocks.
</blockquote></details>

I purposely didn't put it in a message since it's demo code, where I feel the code should be simpler.

---

*[Samples/BlocklySample/BlocklySample/Resources/Non-Localized/Turtle/turtle_blocks.json, line 45 at r1](https://reviewable.io:443/reviews/google/blockly-ios/423#-Koxrr8ezLHKScJBG8EY:-Kp1v7nSFjMWHN_HCBZw:b5q2gtx) ([raw file](https://github.com/google/blockly-ios/blob/f46a32ee0cf8745cbcbdd5193d1c4436322ad7ef/Samples/BlocklySample/BlocklySample/Resources/Non-Localized/Turtle/turtle_blocks.json#L45)):*
<details><summary><i>Previously, RoboErikG wrote…</i></summary><blockquote>

ditto on making these %{refs} in a followup cl.
</blockquote></details>

Same thing.

---

*[Sources/Layout/Default/DefaultLayoutConfig.swift, line 113 at r1](https://reviewable.io:443/reviews/google/blockly-ios/423#-Koxss3BGPLzB3rQDe3h:-Kp1vHU3Jq-P_TAs2G1H:b-896fix) ([raw file](https://github.com/google/blockly-ios/blob/f46a32ee0cf8745cbcbdd5193d1c4436322ad7ef/Sources/Layout/Default/DefaultLayoutConfig.swift#L113)):*
<details><summary><i>Previously, RoboErikG wrote…</i></summary><blockquote>

nit line length
</blockquote></details>

Done.

---

*[Sources/UI/View Controllers/WorkbenchViewController.swift, line 271 at r1](https://reviewable.io:443/reviews/google/blockly-ios/423#-KoxtXiqVgyAFrKRfHcJ:-Kp1vgk29bT7J0SUNQsj:b-896fix) ([raw file](https://github.com/google/blockly-ios/blob/f46a32ee0cf8745cbcbdd5193d1c4436322ad7ef/Sources/UI/View Controllers/WorkbenchViewController.swift#L271)):*
<details><summary><i>Previously, RoboErikG wrote…</i></summary><blockquote>

nit line length here and below.
</blockquote></details>

Done.

---

*[Sources/UI/Views/MutatorProcedureDefinitionView.swift, line 89 at r1](https://reviewable.io:443/reviews/google/blockly-ios/423#-KoxumZVT1f2vocALeF_:-Kp1vlZGTI_c-5yCuKEu:b-896fix) ([raw file](https://github.com/google/blockly-ios/blob/f46a32ee0cf8745cbcbdd5193d1c4436322ad7ef/Sources/UI/Views/MutatorProcedureDefinitionView.swift#L89)):*
<details><summary><i>Previously, RoboErikG wrote…</i></summary><blockquote>

nit ws
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/google/blockly-ios/423#-:-Kp1vmhT8O0oW-ZOP-g7:b4lwugl)*

**Pull request merged**
