### PR TITLE
- Fixes bug with procedure coordinator where it could auto-create a d…

### PR DESCRIPTION
**Pull request by vicng**
…efinition block when it wasn't needed

- Changes Workspace to better handle simultaneous block tree additions/removals
- Changes WorkspaceListener to match new method implementations
- Fixes edge-case bug where dragging a block while editing text field would create two event groups
- Fixes CodeGeneratorServiceTest to match new signatures

---
This change is [Reviewable](https://reviewable.io/reviews/google/blockly-ios/383)

### CODE REVIEW

**Comment by vicng** [comment]
This addresses issue #379 .

**Comment by vicng** [comment]
+@corydcode +@roboerikg 

---

Review status: 0 of 8 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/google/blockly-ios/383#-:-Kj5w5po-Ln0bkYSPrBW:b4ivu6b)*

**Comment by RoboErikG** [comment]
:lgtm:

---

Review status: 0 of 8 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/google/blockly-ios/383#-:-KjK56DS1nk7NLC4_Mwk:bnfp4nl)*

**Comment by CoryDCode** [comment]
Ack - missed this, sorry! I like the change. :lgtm: 

---

Review status: 0 of 8 files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/google/blockly-ios/383#-:-KjKetpynG_LvonW3UOA:b-ersshn)*

**Pull request merged**
