### PR TITLE
Fixing up NameManager so it follows web functionality more closely.

### PR DESCRIPTION
**Pull request by CoryDCode**
This change is [Reviewable](https://reviewable.io/reviews/google/blockly-ios/270)

### CODE REVIEW

**Comment by CoryDCode** [comment]
+@vicng 

---

Review status: 0 of 2 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/google/blockly-ios/270#-:-KWoetVnF3g82uXrsYp6:b-ijk5r)*

**Comment by vicng** [comment]
Can you update the tests?

---

Review status: 0 of 2 files reviewed at latest revision, 3 unresolved discussions.

---

*[Source/Model/FieldVariable.swift, line 36 at r1](https://reviewable.io:443/reviews/google/blockly-ios/270#-KWoqX6grnv0Ds18aUwG:-KWoqX6grnv0Ds18aUwH:bbhkvas) ([raw file](https://github.com/google/blockly-ios/blob/8972ac18bc22622ff0ac7d07332688a3bd51672c/Source/Model/FieldVariable.swift#L36)):*
> ```Swift
>       // to remove the name it was using
>       oldValue?.listeners.remove(self) // Remove
>       oldValue?.removeName(variable)
> ```

The name shouldn't be removed from the previous NameManager. I think that should only happen on an explicit variable delete now.

---

*[Source/Model/FieldVariable.swift, line 39 at r1](https://reviewable.io:443/reviews/google/blockly-ios/270#-KWooR6MAwgi-6HZD8cc:-KWooR6MAwgi-6HZD8cd:b-y17wz5) ([raw file](https://github.com/google/blockly-ios/blob/8972ac18bc22622ff0ac7d07332688a3bd51672c/Source/Model/FieldVariable.swift#L39)):*
> ```Swift
> 
>       // Add name to new nameManager
>       nameManager?.listeners.add(self)
> ```

Rewrite this as:

```
if let newManager = nameManager {
  newManager.listeners.add(self)

  if !newManager.containsName(variable) {
    do {
      try newManager.addName(variable)
        } catch let error {
          bky_assertionFailure("Couldn't add variable: \(error)")
        }
     }
  } else {
    // Updates the new name manager so all variables use the same case-sensitivity
    newManager.renameName(variable, toName: variable)
  }
}
```

---

*[Source/Model/FieldVariable.swift, line 101 at r1](https://reviewable.io:443/reviews/google/blockly-ios/270#-KWopr6JY1ztbbAOw3op:-KWopr6JY1ztbbAOw3oq:b-mvv7z) ([raw file](https://github.com/google/blockly-ios/blob/8972ac18bc22622ff0ac7d07332688a3bd51672c/Source/Model/FieldVariable.swift#L101)):*
> ```Swift
>   public func changeToVariable(_ variable: String) {
>     let oldValue = self.variable
>     if oldValue != variable {
> ```

Why isn't the name manager updated?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/google/blockly-ios/270#-:-KWopye-qg5KfXw5LB9o:b-903wgi)*

**Comment by CoryDCode** [comment]
Done.

---

Review status: 0 of 5 files reviewed at latest revision, 3 unresolved discussions.

---

*[Source/Model/FieldVariable.swift, line 36 at r1](https://reviewable.io:443/reviews/google/blockly-ios/270#-KWoqX6grnv0Ds18aUwG:-KWsoanXnsgiuuvIbL8J:b-e8c0ls) ([raw file](https://github.com/google/blockly-ios/blob/8972ac18bc22622ff0ac7d07332688a3bd51672c/Source/Model/FieldVariable.swift#L36)):*
<details><summary><i>Previously, vicng wrote…</i></summary>
> The name shouldn't be removed from the previous NameManager. I think that should only happen on an explicit variable delete now.
</details>
Good catch, that's true. Done.

---

*[Source/Model/FieldVariable.swift, line 39 at r1](https://reviewable.io:443/reviews/google/blockly-ios/270#-KWooR6MAwgi-6HZD8cc:-KWsp1MmoByR7bJrON49:b-896fix) ([raw file](https://github.com/google/blockly-ios/blob/8972ac18bc22622ff0ac7d07332688a3bd51672c/Source/Model/FieldVariable.swift#L39)):*
<details><summary><i>Previously, vicng wrote…</i></summary>
> Rewrite this as:
> 
> ```
> if let newManager = nameManager {
>   newManager.listeners.add(self)
> 
>   if !newManager.containsName(variable) {
>     do {
>       try newManager.addName(variable)
>         } catch let error {
>           bky_assertionFailure("Couldn't add variable: \(error)")
>         }
>      }
>   } else {
>     // Updates the new name manager so all variables use the same case-sensitivity
>     newManager.renameName(variable, toName: variable)
>   }
> }
> ```
</details>
Done.

---

*[Source/Model/FieldVariable.swift, line 101 at r1](https://reviewable.io:443/reviews/google/blockly-ios/270#-KWopr6JY1ztbbAOw3op:-KWt8F8YBEquFfCcyPoR:b-du4k8a) ([raw file](https://github.com/google/blockly-ios/blob/8972ac18bc22622ff0ac7d07332688a3bd51672c/Source/Model/FieldVariable.swift#L101)):*
<details><summary><i>Previously, vicng wrote…</i></summary>
> Why isn't the name manager updated?
</details>
This shouldn't need to update name manager - a new variable should not be added through this flow. NameManager SHOULD be getting checked for existence, but that should be done in FieldVariableLayout when we move NameManager. I added a TODO there to make sure I do that.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/google/blockly-ios/270#-:-KWt8Xy8twfO-DkxA8Tx:b-896fix)*

**Comment by vicng** [comment]
Review status: 0 of 5 files reviewed at latest revision, 6 unresolved discussions.

---

*[Source/Layout/FieldVariableLayout.swift, line 82 at r2](https://reviewable.io:443/reviews/google/blockly-ios/270#-KWtC6f4uunaFo_d0f3W:-KWtC6f4uunaFo_d0f3X:b-es6wom) ([raw file](https://github.com/google/blockly-ios/blob/87759ca54f9561ca355f768350ecf65f7b256fc8/Source/Layout/FieldVariableLayout.swift#L82)):*
> ```Swift
>     // Setting to a new variable automatically fires a listener to update the layout
> 
>     // TODO: Check name manager for a valid variable name.
> ```

// TODO:(corydiers)

---

*[Source/Model/FieldVariable.swift, line 40 at r2](https://reviewable.io:443/reviews/google/blockly-ios/270#-KWtCEI01-_0IT_gpfbL:-KWtCEI01-_0IT_gpfbM:b5thfbp) ([raw file](https://github.com/google/blockly-ios/blob/87759ca54f9561ca355f768350ecf65f7b256fc8/Source/Model/FieldVariable.swift#L40)):*
> ```Swift
>       nameManager?.listeners.add(self)
>       if let newManager = nameManager {
>         if !newManager.containsName(variable) {
> ```

Move `nameManager.listeners.add(self)` here

---

*[Tests/Source/Control/NameManagerTest.swift, line 90 at r2](https://reviewable.io:443/reviews/google/blockly-ios/270#-KWtCXFCztidNy7y27M7:-KWtCXFCztidNy7y27M8:b-naj3mb) ([raw file](https://github.com/google/blockly-ios/blob/87759ca54f9561ca355f768350ecf65f7b256fc8/Tests/Source/Control/NameManagerTest.swift#L90)):*
> ```Swift
>     listener.clearState()
> 
>     do {
> ```

Use `BKYAssertThrow(...)` here.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/google/blockly-ios/270)*

**Comment by CoryDCode** [comment]
Review status: 0 of 5 files reviewed at latest revision, 6 unresolved discussions.

---

*[Source/Layout/FieldVariableLayout.swift, line 82 at r2](https://reviewable.io:443/reviews/google/blockly-ios/270#-KWtC6f4uunaFo_d0f3W:-KWtFezgZlWzphu5YPzJ:b-896fix) ([raw file](https://github.com/google/blockly-ios/blob/87759ca54f9561ca355f768350ecf65f7b256fc8/Source/Layout/FieldVariableLayout.swift#L82)):*
<details><summary><i>Previously, vicng wrote…</i></summary>
> // TODO:(corydiers)
</details>
Done.

---

*[Source/Model/FieldVariable.swift, line 40 at r2](https://reviewable.io:443/reviews/google/blockly-ios/270#-KWtCEI01-_0IT_gpfbL:-KWtFdgm-1dWZIwhtb08:b-896fix) ([raw file](https://github.com/google/blockly-ios/blob/87759ca54f9561ca355f768350ecf65f7b256fc8/Source/Model/FieldVariable.swift#L40)):*
<details><summary><i>Previously, vicng wrote…</i></summary>
> Move `nameManager.listeners.add(self)` here
</details>
Done.

---

*[Tests/Source/Control/NameManagerTest.swift, line 90 at r2](https://reviewable.io:443/reviews/google/blockly-ios/270#-KWtCXFCztidNy7y27M7:-KWtFeVd5wlhKmGLJGPq:b-896fix) ([raw file](https://github.com/google/blockly-ios/blob/87759ca54f9561ca355f768350ecf65f7b256fc8/Tests/Source/Control/NameManagerTest.swift#L90)):*
<details><summary><i>Previously, vicng wrote…</i></summary>
> Use `BKYAssertThrow(...)` here.
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/google/blockly-ios/270)*

**Comment by vicng** [comment]
:lgtm:

---

Review status: 0 of 5 files reviewed at latest revision, 6 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/google/blockly-ios/270#-:-KWtU14NwNtY4Il9UMjd:bnfp4nl)*

**Pull request merged**
