### PR TITLE
Opens some public methods in WorkbenchViewController and removes obso…

### PR DESCRIPTION
**Pull request by vicng**
…lete code

---
This change is [Reviewable](https://reviewable.io/reviews/google/blockly-ios/436)

### CODE REVIEW

**Comment by vicng** [comment]
+@corydcode +@roboerikg 

---

Review status: 0 of 1 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/google/blockly-ios/436#-:-KqA_WqEdWHllEYJfoV6:b4ivu6b)*

**Comment by CoryDCode** [comment]
Review status: 0 of 1 files reviewed at latest revision, 2 unresolved discussions.

---

*[Sources/UI/View Controllers/WorkbenchViewController.swift, line 736 at r1](https://reviewable.io:443/reviews/google/blockly-ios/436#-KqOlp0I-hP2MbJ9IEgW:-KqOlp0I-hP2MbJ9IEgX:b4bk336) ([raw file](https://github.com/google/blockly-ios/blob/412b283e2068510de820cbbc3a8908548258a885/Sources/UI/View Controllers/WorkbenchViewController.swift#L736)):*
> ```Swift
>    - parameter gesture: The `UIPanGestureRecognizer` that fired the method.
>    */
>   open func didPanWorkspaceView(_ gesture: UIPanGestureRecognizer) {
> ```

Hmm. If these are overridable, developers can disable panning and tapping. Do we want to allow that, or should we define open methods that are called in this function and can be overridden to add functionality without replacing it?

---

*[Sources/UI/View Controllers/WorkbenchViewController.swift, line 1356 at r1](https://reviewable.io:443/reviews/google/blockly-ios/436#-KqOmF0sO9hyg9jR7O7A:-KqOmF0sO9hyg9jR7O7B:bkbbttz) ([raw file](https://github.com/google/blockly-ios/blob/412b283e2068510de820cbbc3a8908548258a885/Sources/UI/View Controllers/WorkbenchViewController.swift#L1356)):*
> ```Swift
> 
> extension WorkbenchViewController: WorkspaceViewControllerDelegate {
>   open func workspaceViewController(
> ```

Similarly here - if these functions get overridden without super getting called, it's probably not what the developer wants. Should we make a different open function that gets called in this function, or are we okay with people screwing things up for themselves? Unfortunately, there's no require_super analogue in Swift.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/google/blockly-ios/436)*

**Comment by vicng** [comment]
Review status: 0 of 1 files reviewed at latest revision, 2 unresolved discussions.

---

*[Sources/UI/View Controllers/WorkbenchViewController.swift, line 736 at r1](https://reviewable.io:443/reviews/google/blockly-ios/436#-KqOlp0I-hP2MbJ9IEgW:-KqUlMzCTtASZL36fuC0:by39d5w) ([raw file](https://github.com/google/blockly-ios/blob/412b283e2068510de820cbbc3a8908548258a885/Sources/UI/View Controllers/WorkbenchViewController.swift#L736)):*
<details><summary><i>Previously, CoryDCode wrote…</i></summary><blockquote>

Hmm. If these are overridable, developers can disable panning and tapping. Do we want to allow that, or should we define open methods that are called in this function and can be overridden to add functionality without replacing it?
</blockquote></details>

As discussed offline, reverted back since developers can add themselves as targets for the gesture recognizer.

---

*[Sources/UI/View Controllers/WorkbenchViewController.swift, line 1356 at r1](https://reviewable.io:443/reviews/google/blockly-ios/436#-KqOmF0sO9hyg9jR7O7A:-KqUnLD8UiqR3BvICYMv:b1qyoj8) ([raw file](https://github.com/google/blockly-ios/blob/412b283e2068510de820cbbc3a8908548258a885/Sources/UI/View Controllers/WorkbenchViewController.swift#L1356)):*
<details><summary><i>Previously, CoryDCode wrote…</i></summary><blockquote>

Similarly here - if these functions get overridden without super getting called, it's probably not what the developer wants. Should we make a different open function that gets called in this function, or are we okay with people screwing things up for themselves? Unfortunately, there's no require_super analogue in Swift.
</blockquote></details>

Keeping open, as discussed offline.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/google/blockly-ios/436)*

**Comment by CoryDCode** [comment]
:lgtm:

---

Review status: 0 of 1 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/google/blockly-ios/436#-:-KqUo_6xgMhzTWM6gaBj:bnfp4nl)*

**Pull request merged**
