### PR TITLE
Changing the turtle demo so the canvas resizes to match what the turt…

### PR DESCRIPTION
**Pull request by CoryDCode**
…le draws.

---
This change is [Reviewable](https://reviewable.io/reviews/google/blockly-ios/468)

### CODE REVIEW

**Comment by vicng** [comment]
Review status: 0 of 5 files reviewed at latest revision, 5 unresolved discussions, some commit checks failed.

---

*[Samples/BlocklySample/BlocklySample/Resources/Non-Localized/Turtle/turtle.js, line 63 at r1](https://reviewable.io:443/reviews/google/blockly-ios/468#-KwHRIPAV0rEXhizklOM:-KwHRIPAV0rEXhizklON:bo3pjw3) ([raw file](https://github.com/google/blockly-ios/blob/0faba578536e97e65511cb6e8d869a82e45196db/Samples/BlocklySample/BlocklySample/Resources/Non-Localized/Turtle/turtle.js#L63)):*
> ```JavaScript
> window.addEventListener('load', Turtle.init);
> 
> Turtle.setBounds = function(width, height) {
> ```

Add comment.

---

*[Samples/BlocklySample/BlocklySample/Resources/Non-Localized/Turtle/turtle.js, line 170 at r1](https://reviewable.io:443/reviews/google/blockly-ios/468#-KwHRZ54_ms2GFcRKIHX:-KwHRZ54_ms2GFcRKIHY:bon6g1r) ([raw file](https://github.com/google/blockly-ios/blob/0faba578536e97e65511cb6e8d869a82e45196db/Samples/BlocklySample/BlocklySample/Resources/Non-Localized/Turtle/turtle.js#L170)):*
> ```JavaScript
>   window.LoopTrap = 1000;
> 
>   Turtle.fakeX = Turtle.WIDTH / 2;
> ```

Add comments for these properties.

---

*[Samples/BlocklySample/BlocklySample/Resources/Non-Localized/Turtle/turtle.js, line 298 at r1](https://reviewable.io:443/reviews/google/blockly-ios/468#-KwHSeGl14EUb2UWsodV:-KwHSeGl14EUb2UWsodW:b-6y27kt) ([raw file](https://github.com/google/blockly-ios/blob/0faba578536e97e65511cb6e8d869a82e45196db/Samples/BlocklySample/BlocklySample/Resources/Non-Localized/Turtle/turtle.js#L298)):*
> ```JavaScript
>   if (Turtle.fakeX > Turtle.WIDTH || Turtle.fakeX < 0) {
>     if (Turtle.fakeX < 0) {
>       Turtle.x -= xDelta;
> ```

Why does this move the turtle? 

---

*[Samples/BlocklySample/BlocklySample/Resources/Non-Localized/Turtle/turtle.js, line 306 at r1](https://reviewable.io:443/reviews/google/blockly-ios/468#-KwHSj0zQlb0DRfjusTL:-KwHSj0zQlb0DRfjusTM:bhey2on) ([raw file](https://github.com/google/blockly-ios/blob/0faba578536e97e65511cb6e8d869a82e45196db/Samples/BlocklySample/BlocklySample/Resources/Non-Localized/Turtle/turtle.js#L306)):*
> ```JavaScript
>   if (Turtle.fakeY > Turtle.HEIGHT || Turtle.fakeY < 0) {
>     if (Turtle.fakeY < 0) {
>       Turtle.y += yDelta;
> ```

Same thing here

---

*[Samples/BlocklySample/BlocklySample/Sources/TurtleSwiftViewController.swift, line 24 at r1](https://reviewable.io:443/reviews/google/blockly-ios/468#-KwHTKj0-xH__D8PveKI:-KwHTKj0-xH__D8PveKJ:b5iojd0) ([raw file](https://github.com/google/blockly-ios/blob/0faba578536e97e65511cb6e8d869a82e45196db/Samples/BlocklySample/BlocklySample/Sources/TurtleSwiftViewController.swift#L24)):*
> ```Swift
>  */
> class TurtleSwiftViewController: UIViewController,
>     TurtleViewControllerInterface, WKNavigationDelegate {
> ```

Declare this in a Swift extension and move the webView(...) method into that.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/google/blockly-ios/468)*

**Comment by CoryDCode** [comment]
Review status: 0 of 5 files reviewed at latest revision, 5 unresolved discussions, some commit checks failed.

---

*[Samples/BlocklySample/BlocklySample/Resources/Non-Localized/Turtle/turtle.js, line 63 at r1](https://reviewable.io:443/reviews/google/blockly-ios/468#-KwHRIPAV0rEXhizklOM:-KwI2GG5oE53pJcGZ-Iq:b-896fix) ([raw file](https://github.com/google/blockly-ios/blob/0faba578536e97e65511cb6e8d869a82e45196db/Samples/BlocklySample/BlocklySample/Resources/Non-Localized/Turtle/turtle.js#L63)):*
<details><summary><i>Previously, vicng wrote…</i></summary><blockquote>

Add comment.
</blockquote></details>

Done.

---

*[Samples/BlocklySample/BlocklySample/Resources/Non-Localized/Turtle/turtle.js, line 170 at r1](https://reviewable.io:443/reviews/google/blockly-ios/468#-KwHRZ54_ms2GFcRKIHX:-KwI2Gj2wF1ni6ZEtgSW:b-896fix) ([raw file](https://github.com/google/blockly-ios/blob/0faba578536e97e65511cb6e8d869a82e45196db/Samples/BlocklySample/BlocklySample/Resources/Non-Localized/Turtle/turtle.js#L170)):*
<details><summary><i>Previously, vicng wrote…</i></summary><blockquote>

Add comments for these properties.
</blockquote></details>

Done.

---

*[Samples/BlocklySample/BlocklySample/Resources/Non-Localized/Turtle/turtle.js, line 298 at r1](https://reviewable.io:443/reviews/google/blockly-ios/468#-KwHSeGl14EUb2UWsodV:-KwI2HZ1N_PpaHUHaXc_:b-xjsgai) ([raw file](https://github.com/google/blockly-ios/blob/0faba578536e97e65511cb6e8d869a82e45196db/Samples/BlocklySample/BlocklySample/Resources/Non-Localized/Turtle/turtle.js#L298)):*
<details><summary><i>Previously, vicng wrote…</i></summary><blockquote>

Why does this move the turtle? 
</blockquote></details>

Because the canvas only grows down and to the right. So when the turtle walks off the left or top of the canvas, we move the turtle to compensate. I'll add a comment.

---

*[Samples/BlocklySample/BlocklySample/Resources/Non-Localized/Turtle/turtle.js, line 306 at r1](https://reviewable.io:443/reviews/google/blockly-ios/468#-KwHSj0zQlb0DRfjusTL:-KwI2hxv8WErUaF0srgm:b-896fix) ([raw file](https://github.com/google/blockly-ios/blob/0faba578536e97e65511cb6e8d869a82e45196db/Samples/BlocklySample/BlocklySample/Resources/Non-Localized/Turtle/turtle.js#L306)):*
<details><summary><i>Previously, vicng wrote…</i></summary><blockquote>

Same thing here
</blockquote></details>

Done.

---

*[Samples/BlocklySample/BlocklySample/Sources/TurtleSwiftViewController.swift, line 24 at r1](https://reviewable.io:443/reviews/google/blockly-ios/468#-KwHTKj0-xH__D8PveKI:-KwI3RctVo2vnukd5Rgn:b-vpethj) ([raw file](https://github.com/google/blockly-ios/blob/0faba578536e97e65511cb6e8d869a82e45196db/Samples/BlocklySample/BlocklySample/Sources/TurtleSwiftViewController.swift#L24)):*
<details><summary><i>Previously, vicng wrote…</i></summary><blockquote>

Declare this in a Swift extension and move the webView(...) method into that.
</blockquote></details>

Oh, duh. Thanks - done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/google/blockly-ios/468)*

**Comment by vicng** [comment]
Review status: 0 of 5 files reviewed at latest revision, 5 unresolved discussions, some commit checks failed.

---

*[Samples/BlocklySample/BlocklySample/Resources/Non-Localized/Turtle/turtle.js, line 298 at r1](https://reviewable.io:443/reviews/google/blockly-ios/468#-KwHSeGl14EUb2UWsodV:-KwMbYEJFP25FxMUwc3B:b-xczzna) ([raw file](https://github.com/google/blockly-ios/blob/0faba578536e97e65511cb6e8d869a82e45196db/Samples/BlocklySample/BlocklySample/Resources/Non-Localized/Turtle/turtle.js#L298)):*
<details><summary><i>Previously, CoryDCode wrote…</i></summary><blockquote>

Because the canvas only grows down and to the right. So when the turtle walks off the left or top of the canvas, we move the turtle to compensate. I'll add a comment.
</blockquote></details>

I thought this method is supposed to fake a move, not actually move the turtle.

I think there should be another property called "startingPositionX"/"startingPositionY" and then before the program is run, it sets "x"/"y" to those values.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/google/blockly-ios/468)*

**Comment by CoryDCode** [comment]
Review status: 0 of 5 files reviewed at latest revision, 5 unresolved discussions, some commit checks failed.

---

*[Samples/BlocklySample/BlocklySample/Resources/Non-Localized/Turtle/turtle.js, line 298 at r1](https://reviewable.io:443/reviews/google/blockly-ios/468#-KwHSeGl14EUb2UWsodV:-KwMpxlpDLPyf9GILW6m:b-896fix) ([raw file](https://github.com/google/blockly-ios/blob/0faba578536e97e65511cb6e8d869a82e45196db/Samples/BlocklySample/BlocklySample/Resources/Non-Localized/Turtle/turtle.js#L298)):*
<details><summary><i>Previously, vicng wrote…</i></summary><blockquote>

I thought this method is supposed to fake a move, not actually move the turtle.

I think there should be another property called "startingPositionX"/"startingPositionY" and then before the program is run, it sets "x"/"y" to those values.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/google/blockly-ios/468)*

**Comment by vicng** [comment]
:lgtm:

---

Review status: 0 of 5 files reviewed at latest revision, 6 unresolved discussions, some commit checks failed.

---

*[Samples/BlocklySample/BlocklySample/Resources/Non-Localized/Turtle/turtle.js, line 301 at r2](https://reviewable.io:443/reviews/google/blockly-ios/468#-KwMsHbsiZPfYrZ7cmlQ:-KwMsHbsiZPfYrZ7cmlR:b-odgstt) ([raw file](https://github.com/google/blockly-ios/blob/daf7262409b15a8adf62bb6644eaf8bb18c419ee/Samples/BlocklySample/BlocklySample/Resources/Non-Localized/Turtle/turtle.js#L301)):*
> ```JavaScript
> // Canvas measurement
> 
> // Fake all of the moves, and resize the canvas so the turtle fits in the canvas when it draws.
> ```

Update comment to include starting position.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/google/blockly-ios/468#-:-KwMsXS-bHBpIh3Map9Y:bnfp4nl)*

**Comment by CoryDCode** [comment]
Review status: 0 of 5 files reviewed at latest revision, 6 unresolved discussions, some commit checks failed.

---

*[Samples/BlocklySample/BlocklySample/Resources/Non-Localized/Turtle/turtle.js, line 301 at r2](https://reviewable.io:443/reviews/google/blockly-ios/468#-KwMsHbsiZPfYrZ7cmlQ:-KwMuR0-jDwlY4kbxKUH:b-896fix) ([raw file](https://github.com/google/blockly-ios/blob/daf7262409b15a8adf62bb6644eaf8bb18c419ee/Samples/BlocklySample/BlocklySample/Resources/Non-Localized/Turtle/turtle.js#L301)):*
<details><summary><i>Previously, vicng wrote…</i></summary><blockquote>

Update comment to include starting position.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/google/blockly-ios/468)*

**Pull request merged**
