### PR TITLE
Fixes if-return block so it's automatically disabled if it isn't conn…

### PR DESCRIPTION
**Pull request by vicng**
…ected to a procedure definition block

---
This change is [Reviewable](https://reviewable.io/reviews/google/blockly-ios/479)

### CODE REVIEW

**Comment by vicng** [comment]
+@corydcode 

---

Review status: 0 of 1 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/google/blockly-ios/479#-:-KxLaYvy_HAFSew965bz:b-q78qn8)*

**Comment by CoryDCode** [comment]
Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion.

---

*[Sources/Control/ProcedureCoordinator.swift, line 387 at r1](https://reviewable.io:443/reviews/google/blockly-ios/479#-KxOuMP9eA6VNPOPlgXb:-KxOuMP9eA6VNPOPlgXc:b5bgx98) ([raw file](https://github.com/google/blockly-ios/blob/1ff3768dec5a1441251005b95346f77781d86576/Sources/Control/ProcedureCoordinator.swift#L387)):*
> ```Swift
>     // If it's being moved to the trash can, we want to re-enable the if-return block (which will
>     // happen on validation).
>     validateIfReturnBlock(block)
> ```

Do we want to do this here? Should we instead re-enable all blocks that enter the trash, regardless of origin?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/google/blockly-ios/479)*

**Comment by vicng** [comment]
Review status: 0 of 2 files reviewed at latest revision, 1 unresolved discussion.

---

*[Sources/Control/ProcedureCoordinator.swift, line 387 at r1](https://reviewable.io:443/reviews/google/blockly-ios/479#-KxOuMP9eA6VNPOPlgXb:-KxPfS2rrsGTzkkIphVA:bt2vr1b) ([raw file](https://github.com/google/blockly-ios/blob/1ff3768dec5a1441251005b95346f77781d86576/Sources/Control/ProcedureCoordinator.swift#L387)):*
<details><summary><i>Previously, CoryDCode wrote…</i></summary><blockquote>

Do we want to do this here? Should we instead re-enable all blocks that enter the trash, regardless of origin?
</blockquote></details>

Fixed.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/google/blockly-ios/479)*

**Comment by CoryDCode** [comment]
:lgtm:

---

Review status: 0 of 2 files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/google/blockly-ios/479#-:-KxPgNPYsZnInwDtfnsa:bnfp4nl)*

**Pull request merged**
