### PR TITLE
- Added UI option for rendering a Start Hat.

### PR DESCRIPTION
**Pull request by vicng**
- Updated LayoutConfig to support Bool
- Fixed BlockLayout to render blocks with an empty message
- Removed male/female naming of block layout background properties

---
This change is [Reviewable](https://reviewable.io/reviews/google/blockly-ios/265)

### CODE REVIEW

**Comment by vicng** [comment]
+@corydcode 



---

Review status: 0 of 6 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/google/blockly-ios/265#-:-KWdrhaw7TKncKNoUQGB:b-kzr4nf)*

**Comment by CoryDCode** [comment]
Review status: 0 of 6 files reviewed at latest revision, 1 unresolved discussion.

---

*[Source/Layout/Default/DefaultBlockLayout+Background.swift, line 67 at r1](https://reviewable.io:443/reviews/google/blockly-ios/265#-KWdvhXGYYovEarWTMx-:-KWdvhXHO0nUJJ9IMBrN:b-j9tden) ([raw file](https://github.com/google/blockly-ios/blob/18fb41eb1f26d9bfbcb5045853ddec468013fbda/Source/Layout/Default/DefaultBlockLayout+Background.swift#L67)):*
> ```Swift
>       self.previousStatementConnector = (layout.block.previousConnection != nil)
>       self.nextStatementConnector = (layout.block.nextConnection != nil)
>       self.startHat = !previousStatementConnector && !outputConnector &&
> ```

Do we need to log an error if previousStatementConnector and start hat are set at once?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/google/blockly-ios/265)*

**Comment by vicng** [comment]
Review status: 0 of 6 files reviewed at latest revision, 1 unresolved discussion.

---

*[Source/Layout/Default/DefaultBlockLayout+Background.swift, line 67 at r1](https://reviewable.io:443/reviews/google/blockly-ios/265#-KWdvhXGYYovEarWTMx-:-KWe7bKs7iFgdOYF_3if:befx2u0) ([raw file](https://github.com/google/blockly-ios/blob/18fb41eb1f26d9bfbcb5045853ddec468013fbda/Source/Layout/Default/DefaultBlockLayout+Background.swift#L67)):*
<details><summary><i>Previously, CoryDCode wrote…</i></summary>
> Do we need to log an error if previousStatementConnector and start hat are set at once?
</details>
I don't think so -- startHat depends on previous/output flags not being set and all those properties can only be updated within this file.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/google/blockly-ios/265)*

**Comment by CoryDCode** [comment]
Review status: 0 of 6 files reviewed at latest revision, 1 unresolved discussion.

---

*[Source/Layout/Default/DefaultBlockLayout+Background.swift, line 67 at r1](https://reviewable.io:443/reviews/google/blockly-ios/265#-KWdvhXGYYovEarWTMx-:-KWeFRhLqwmYLNPfLsQF:b-1x2epe) ([raw file](https://github.com/google/blockly-ios/blob/18fb41eb1f26d9bfbcb5045853ddec468013fbda/Source/Layout/Default/DefaultBlockLayout+Background.swift#L67)):*
<details><summary><i>Previously, vicng wrote…</i></summary>
> I don't think so -- startHat depends on previous/output flags not being set and all those properties can only be updated within this file.
</details>
But the block definition can allow for both, right? This may not be where we need to stop that, but if the block JSON/XML has both, that's an error, yes?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/google/blockly-ios/265)*

**Comment by vicng** [comment]
Review status: 0 of 6 files reviewed at latest revision, 1 unresolved discussion.

---

*[Source/Layout/Default/DefaultBlockLayout+Background.swift, line 67 at r1](https://reviewable.io:443/reviews/google/blockly-ios/265#-KWdvhXGYYovEarWTMx-:-KWeHc6rRNclJYIqNgzl:bblw6pz) ([raw file](https://github.com/google/blockly-ios/blob/18fb41eb1f26d9bfbcb5045853ddec468013fbda/Source/Layout/Default/DefaultBlockLayout+Background.swift#L67)):*
<details><summary><i>Previously, CoryDCode wrote…</i></summary>
> But the block definition can allow for both, right? This may not be where we need to stop that, but if the block JSON/XML has both, that's an error, yes?
</details>
The start hat isn't a property on the block (like previous/output). It's only set based on previous/output being false and the engine.config flag being set.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/google/blockly-ios/265)*

**Comment by vicng** [comment]
Review status: 0 of 6 files reviewed at latest revision, 1 unresolved discussion.

---

*[Source/Layout/Default/DefaultBlockLayout+Background.swift, line 67 at r1](https://reviewable.io:443/reviews/google/blockly-ios/265#-KWdvhXGYYovEarWTMx-:-KWeIHGpJ2C7tFg4JdGT:b-mr6ja5) ([raw file](https://github.com/google/blockly-ios/blob/18fb41eb1f26d9bfbcb5045853ddec468013fbda/Source/Layout/Default/DefaultBlockLayout+Background.swift#L67)):*
<details><summary><i>Previously, vicng wrote…</i></summary>
> The start hat isn't a property on the block (like previous/output). It's only set based on previous/output being false and the engine.config flag being set.
</details>
Start hat is essentially a global rendering flag.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/google/blockly-ios/265)*

**Comment by CoryDCode** [comment]
Review status: 0 of 6 files reviewed at latest revision, 1 unresolved discussion.

---

*[Source/Layout/Default/DefaultBlockLayout+Background.swift, line 67 at r1](https://reviewable.io:443/reviews/google/blockly-ios/265#-KWdvhXGYYovEarWTMx-:-KWeIvJqAHxNR7Zi-fls:b-c7vyx5) ([raw file](https://github.com/google/blockly-ios/blob/18fb41eb1f26d9bfbcb5045853ddec468013fbda/Source/Layout/Default/DefaultBlockLayout+Background.swift#L67)):*
<details><summary><i>Previously, vicng wrote…</i></summary>
> Start hat is essentially a global rendering flag.
</details>
Ah. Well, ignore me, then.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/google/blockly-ios/265)*

**Comment by CoryDCode** [comment]
:lgtm:

---

Review status: 0 of 6 files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/google/blockly-ios/265#-:-KWeIy05GV0isgHIzMkD:bnfp4nl)*

**Pull request merged**
