### PR TITLE
Adds method to set viewport of workspace

### PR DESCRIPTION
**Pull request by vicng**
This change is [Reviewable](https://reviewable.io/reviews/google/blockly-ios/442)

### CODE REVIEW

**Comment by vicng** [comment]
+@corydcode +@roboerikg 

---

Review status: 0 of 2 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/google/blockly-ios/442#-:-KrsVOqov6dNs8JT7GDh:b4ivu6b)*

**Comment by CoryDCode** [comment]
Review status: 0 of 2 files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[Sources/UI/Views/WorkspaceView.swift, line 264 at r1](https://reviewable.io:443/reviews/google/blockly-ios/442#-Ks5-ZyGXW9CryBOZM6I:-Ks5-ZyGXW9CryBOZM6J:bfopunr) ([raw file](https://github.com/google/blockly-ios/blob/dfccaf321ad7a5aa347df49e606c214026fcfc09/Sources/UI/Views/WorkspaceView.swift#L264)):*
> ```Swift
>    - note: See `scrollIntoViewEdgeInsets`.
>    */
>   open func setViewport(to location: ViewportLocation, animated: Bool) {
> ```

I'm not sure I understand the purpose of this method. Or rather, I'm not sure I understand why this is the only method to do this, other than allowing arbitrary locations/scrolling a block to center/an edge with padding.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/google/blockly-ios/442)*

**Comment by vicng** [comment]
Review status: 0 of 4 files reviewed at latest revision, 1 unresolved discussion.

---

*[Sources/UI/Views/WorkspaceView.swift, line 264 at r1](https://reviewable.io:443/reviews/google/blockly-ios/442#-Ks5-ZyGXW9CryBOZM6I:-Ks7kxfSlN1I2_hWXOMx:bp0vgg8) ([raw file](https://github.com/google/blockly-ios/blob/dfccaf321ad7a5aa347df49e606c214026fcfc09/Sources/UI/Views/WorkspaceView.swift#L264)):*
<details><summary><i>Previously, CoryDCode wrote…</i></summary><blockquote>

I'm not sure I understand the purpose of this method. Or rather, I'm not sure I understand why this is the only method to do this, other than allowing arbitrary locations/scrolling a block to center/an edge with padding.
</blockquote></details>

As discussed offline, merged this functionality with the `scrollBlockIntoView(...)` method.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/google/blockly-ios/442)*

**Comment by CoryDCode** [comment]
Looks great, thanks for this. :lgtm: 

---

Review status: 0 of 4 files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/google/blockly-ios/442#-:-KsA60y9ochyu11UsjZ-:b-j0urdm)*

**Pull request merged**
