### PR TITLE
Fixing duplicate variable blocks when a variable rename causes a coll…

### PR DESCRIPTION
**Pull request by CoryDCode**
…ision.

Also fixed the name manager calling rename callbacks when a new variable is created.

---
This change is [Reviewable](https://reviewable.io/reviews/google/blockly-ios/296)

### CODE REVIEW

**Comment by CoryDCode** [comment]
+@vicng +@roboerikg 

---

Review status: 0 of 2 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/google/blockly-ios/296#-:-KbCuzvC6st25qeU-adS:bneml20)*

**Comment by vicng** [comment]
Review status: 0 of 2 files reviewed at latest revision, 2 unresolved discussions.

---

*[Source/Control/NameManager.swift, line 148 at r1](https://reviewable.io:443/reviews/google/blockly-ios/296#-KbDOq3BkcIxlEEfdgTc:-KbDOq3BkcIxlEEfdgTd:b8q1ihj) ([raw file](https://github.com/google/blockly-ios/blob/89d08e0ae9d3268c956faab862f33f172983254d/Source/Control/NameManager.swift#L148)):*
> ```Swift
> 
>     guard let oldNameDisplay = _names[oldNameKey],
>       oldNameKey != newNameKey else
> ```

Hmm, this stops renames like:
"test" -> "Test"

---

*[Source/Control/NameManager.swift, line 160 at r1](https://reviewable.io:443/reviews/google/blockly-ios/296#-KbDY2Q-2gVku65asaI_:-KbDY2Q0EO99cW9unI9h:b-hh1ei0) ([raw file](https://github.com/google/blockly-ios/blob/89d08e0ae9d3268c956faab862f33f172983254d/Source/Control/NameManager.swift#L160)):*
> ```Swift
>     }
> 
>     if previousDisplayNameForNewName != nil,
> ```

Use `&&` instead of `,` (I wonder if Apple will deprecate `&&` in Swift 4...)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/google/blockly-ios/296)*

**Comment by CoryDCode** [comment]
Review status: 0 of 2 files reviewed at latest revision, 2 unresolved discussions.

---

*[Source/Control/NameManager.swift, line 148 at r1](https://reviewable.io:443/reviews/google/blockly-ios/296#-KbDOq3BkcIxlEEfdgTc:-KbDez0B3xJ53VfpELwt:b-5d81dp) ([raw file](https://github.com/google/blockly-ios/blob/89d08e0ae9d3268c956faab862f33f172983254d/Source/Control/NameManager.swift#L148)):*
<details><summary><i>Previously, vicng wrote…</i></summary><blockquote>

Hmm, this stops renames like:
"test" -> "Test"
</blockquote></details>

Whoops - oldName != newName. Done

---

*[Source/Control/NameManager.swift, line 160 at r1](https://reviewable.io:443/reviews/google/blockly-ios/296#-KbDY2Q-2gVku65asaI_:-KbDf176Wwln2eWtqE6N:bvu6wxr) ([raw file](https://github.com/google/blockly-ios/blob/89d08e0ae9d3268c956faab862f33f172983254d/Source/Control/NameManager.swift#L160)):*
<details><summary><i>Previously, vicng wrote…</i></summary><blockquote>

Use `&&` instead of `,` (I wonder if Apple will deprecate `&&` in Swift 4...)
</blockquote></details>

Done. (I'm not going to lie, I kind of like the way it writes kind of like a sentence, but yeah, && is better here.)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/google/blockly-ios/296)*

**Comment by vicng** [comment]
Minor nits, but :lgtm: after.

---

Review status: 0 of 2 files reviewed at latest revision, 2 unresolved discussions.

---

*[Source/Control/NameManager.swift, line 148 at r1](https://reviewable.io:443/reviews/google/blockly-ios/296#-KbDOq3BkcIxlEEfdgTc:-KbHfvH6U3HadJGpgOIf:b-gjklx) ([raw file](https://github.com/google/blockly-ios/blob/89d08e0ae9d3268c956faab862f33f172983254d/Source/Control/NameManager.swift#L148)):*
<details><summary><i>Previously, CoryDCode wrote…</i></summary><blockquote>

Whoops - oldName != newName. Done
</blockquote></details>

Could you add a test to NameManagerTest for the two cases here and below?

Btw, you'll need to merge from develop branch (the test target broke in a previous CL).

---

*[Source/Control/NameManager.swift, line 160 at r1](https://reviewable.io:443/reviews/google/blockly-ios/296#-KbDY2Q-2gVku65asaI_:-KbHfpsOGclEkalL_ld8:b-2mx104) ([raw file](https://github.com/google/blockly-ios/blob/89d08e0ae9d3268c956faab862f33f172983254d/Source/Control/NameManager.swift#L160)):*
<details><summary><i>Previously, CoryDCode wrote…</i></summary><blockquote>

Done. (I'm not going to lie, I kind of like the way it writes kind of like a sentence, but yeah, && is better here.)
</blockquote></details>

Can this fit on one line?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/google/blockly-ios/296#-:-KbHg5R_nndq8eV71voy:b-o7tguv)*

**Comment by CoryDCode** [comment]
Review status: 0 of 3 files reviewed at latest revision, 2 unresolved discussions.

---

*[Source/Control/NameManager.swift, line 148 at r1](https://reviewable.io:443/reviews/google/blockly-ios/296#-KbDOq3BkcIxlEEfdgTc:-KbIHnwpIC51rbAFmMzk:b-896fix) ([raw file](https://github.com/google/blockly-ios/blob/89d08e0ae9d3268c956faab862f33f172983254d/Source/Control/NameManager.swift#L148)):*
<details><summary><i>Previously, vicng wrote…</i></summary><blockquote>

Could you add a test to NameManagerTest for the two cases here and below?

Btw, you'll need to merge from develop branch (the test target broke in a previous CL).
</blockquote></details>

Done.

---

*[Source/Control/NameManager.swift, line 160 at r1](https://reviewable.io:443/reviews/google/blockly-ios/296#-KbDY2Q-2gVku65asaI_:-KbI9dXjO5EQpYHaks3z:b-896fix) ([raw file](https://github.com/google/blockly-ios/blob/89d08e0ae9d3268c956faab862f33f172983254d/Source/Control/NameManager.swift#L160)):*
<details><summary><i>Previously, vicng wrote…</i></summary><blockquote>

Can this fit on one line?
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/google/blockly-ios/296)*

**Pull request merged**
