### PR TITLE
- Fixes block rendering so that the first rows of connected blocks ar…

### PR DESCRIPTION
**Pull request by vicng**
…e vertically aligned

---
This change is [Reviewable](https://reviewable.io/reviews/google/blockly-ios/417)

### CODE REVIEW

**Comment by vicng** [comment]
+@corydcode  +@roboerikg



FYI, things still look a bit off right now because fields/block heights aren't normalized. That'll be fixed in the next CL.

---

Review status: 0 of 7 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/google/blockly-ios/417#-:-KnMc2NWJJ_pArSMV08D:bxm3ue1)*

**Comment by RoboErikG** [comment]
:lgtm_strong: This looks really good! Now we just have to figure out how to port it to web.

---

Review status: 0 of 7 files reviewed at latest revision, 3 unresolved discussions.

---

*[Sources/Layout/Default/DefaultBlockLayout+Background.swift, line 139 at r1](https://reviewable.io:443/reviews/google/blockly-ios/417#-Kn_ZCYMpuBP_2-8rjt_:-Kn_ZCYMpuBP_2-8rjta:b-1vvc7j) ([raw file](https://github.com/google/blockly-ios/blob/d985abda6c346f42f51350ee721632381f58e95e/Sources/Layout/Default/DefaultBlockLayout+Background.swift#L139)):*
> ```Swift
>     public var bottomPadding: CGFloat = 0
> 
>     /// The height of the middle part of the row, expressed as a Workspace coordinate system value.
> ```

The height of the portion of the row fields are laid out in? This comment is a little vague on how it's used, especially after this change.

---

*[Sources/Layout/Default/DefaultInputLayout.swift, line 417 at r1](https://reviewable.io:443/reviews/google/blockly-ios/417#-Kn_akUtGLd0F9N3ihhR:-Kn_akUtGLd0F9N3ihhS:b-n0jdrs) ([raw file](https://github.com/google/blockly-ios/blob/d985abda6c346f42f51350ee721632381f58e95e/Sources/Layout/Default/DefaultInputLayout.swift#L417)):*
> ```Swift
>   internal func verticallyAlignRow(toHeight rowHeight: CGFloat) {
>     guard rowHeight >= firstLineHeight else { return }
>     
> ```

nit ws

---

*[Sources/UI/Views/Default/DefaultBlockView.swift, line 391 at r1](https://reviewable.io:443/reviews/google/blockly-ios/417#-Kn_bp-UbBMf5CRCxSh9:-Kn_bp-UbBMf5CRCxShA:b-k3m9wa) ([raw file](https://github.com/google/blockly-ios/blob/d985abda6c346f42f51350ee721632381f58e95e/Sources/UI/Views/Default/DefaultBlockView.swift#L391)):*
> ```Swift
>         path.addLineTo(x: -xEdgeWidth, y: 0, relative: true)
>         // Start left edge
>         path.addLineTo(x: 0, y: inlineConnector.firstLineHeight - inlineConnector.size.height, relative: true)
> ```

nit line length

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/google/blockly-ios/417#-:-Kn_brOzn17XqSFWDZ2V:b-25zq0d)*

**Comment by CoryDCode** [comment]
:lgtm:

---

Review status: 0 of 7 files reviewed at latest revision, 3 unresolved discussions, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/google/blockly-ios/417#-:-Kn_p5VTG_xX4MrqsNHz:bnfp4nl)*

**Comment by vicng** [comment]
Review status: 0 of 7 files reviewed at latest revision, 3 unresolved discussions, some commit checks pending.

---

*[Sources/Layout/Default/DefaultBlockLayout+Background.swift, line 139 at r1](https://reviewable.io:443/reviews/google/blockly-ios/417#-Kn_ZCYMpuBP_2-8rjt_:-Knb3d65Pa_AWXktjWeP:b-896fix) ([raw file](https://github.com/google/blockly-ios/blob/d985abda6c346f42f51350ee721632381f58e95e/Sources/Layout/Default/DefaultBlockLayout+Background.swift#L139)):*
<details><summary><i>Previously, RoboErikG wrote…</i></summary><blockquote>

The height of the portion of the row fields are laid out in? This comment is a little vague on how it's used, especially after this change.
</blockquote></details>

Done.

---

*[Sources/Layout/Default/DefaultInputLayout.swift, line 417 at r1](https://reviewable.io:443/reviews/google/blockly-ios/417#-Kn_akUtGLd0F9N3ihhR:-Knb3AySYXB12BArd0Cv:b-896fix) ([raw file](https://github.com/google/blockly-ios/blob/d985abda6c346f42f51350ee721632381f58e95e/Sources/Layout/Default/DefaultInputLayout.swift#L417)):*
<details><summary><i>Previously, RoboErikG wrote…</i></summary><blockquote>

nit ws
</blockquote></details>

Done.

---

*[Sources/UI/Views/Default/DefaultBlockView.swift, line 391 at r1](https://reviewable.io:443/reviews/google/blockly-ios/417#-Kn_bp-UbBMf5CRCxSh9:-Knb3GQewzO9l_2ShE1M:b-896fix) ([raw file](https://github.com/google/blockly-ios/blob/d985abda6c346f42f51350ee721632381f58e95e/Sources/UI/Views/Default/DefaultBlockView.swift#L391)):*
<details><summary><i>Previously, RoboErikG wrote…</i></summary><blockquote>

nit line length
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/google/blockly-ios/417)*

**Pull request merged**
