### PR TITLE
- Added mutator for editing procedure definition blocks

### PR DESCRIPTION
**Pull request by vicng**
- Updated set of default blocks created for procedure toolbox category

---
This change is [Reviewable](https://reviewable.io/reviews/google/blockly-ios/295)

### CODE REVIEW

**Comment by vicng** [comment]
+@corydcode 




---

Review status: 0 of 9 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/google/blockly-ios/295#-:-KbCeGVTjfnW7b4o3TKn:b-qddvwa)*

**Comment by RoboErikG** [comment]
high level lgtm. Give Cory a chance to review the code a bit closer.

---

Review status: 0 of 9 files reviewed at latest revision, 2 unresolved discussions.

---

*[Source/Layout/MutatorProcedureDefinitionLayout.swift, line 114 at r1](https://reviewable.io:443/reviews/google/blockly-ios/295#-KbGVERyLbxTcZ64NhPx:-KbGVERyLbxTcZ64NhPy:b-n0jdrs) ([raw file](https://github.com/google/blockly-ios/blob/36f14b2ab320d873cc8e81fe1b51fab565ae35dd/Source/Layout/MutatorProcedureDefinitionLayout.swift#L114)):*
> ```Swift
>   /**
>    Returns whether or not the mutator contains duplicate parameters.
>    
> ```

nit ws

---

*[Source/UI/Views/MutatorProcedureDefinitionView.swift, line 218 at r1](https://reviewable.io:443/reviews/google/blockly-ios/295#-KbGVtnlyG1ZS9MOtqJO:-KbGVtnmk4plTx7MZZSe:b-k3m9wa) ([raw file](https://github.com/google/blockly-ios/blob/36f14b2ab320d873cc8e81fe1b51fab565ae35dd/Source/UI/Views/MutatorProcedureDefinitionView.swift#L218)):*
> ```Swift
>   }
> 
>   override func tableView(_ tableView: UITableView, willDisplayHeaderView view: UIView, forSection section: Int) {
> ```

nit line length

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/google/blockly-ios/295#-:-KbGW9dX7B54tgvbKrHr:b-bmsqi3)*

**Comment by CoryDCode** [comment]
:lgtm:

---

Reviewed 2 of 9 files at r1.
Review status: 2 of 9 files reviewed at latest revision, 4 unresolved discussions.

---

*[Source/UI/Views/MutatorProcedureDefinitionView.swift, line 232 at r1](https://reviewable.io:443/reviews/google/blockly-ios/295#-KbHNjZJU-3bWpvrNdyP:-KbHNjZJU-3bWpvrNdyQ:b-6iks79) ([raw file](https://github.com/google/blockly-ios/blob/36f14b2ab320d873cc8e81fe1b51fab565ae35dd/Source/UI/Views/MutatorProcedureDefinitionView.swift#L232)):*
> ```Swift
>       case SECTION_PARAMETERS:
>         let errorMessage = self.parametersErrorMessage()
>         let errorFont = UIFont.systemFont(ofSize: 14)
> ```

Not GlobalFont?

---

*[Source/UI/Views/MutatorProcedureDefinitionView.swift, line 234 at r1](https://reviewable.io:443/reviews/google/blockly-ios/295#-KbHNmZ3KhXmCTSyN5_n:-KbHNmZ3KhXmCTSyN5_o:b-exqphn) ([raw file](https://github.com/google/blockly-ios/blob/36f14b2ab320d873cc8e81fe1b51fab565ae35dd/Source/UI/Views/MutatorProcedureDefinitionView.swift#L234)):*
> ```Swift
>         let errorFont = UIFont.systemFont(ofSize: 14)
>         let errorSize = errorMessage.bky_multiLineSize(
>           forFont: errorFont, constrainedToWidth: tableView.contentSize.width - 30)
> ```

Could we add a todo to change this from magic numbers?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/google/blockly-ios/295#-:-KbHNpn1TPYH9-Dy5Ld_:bnfp4nl)*

**Comment by vicng** [comment]
Review status: 2 of 13 files reviewed at latest revision, 4 unresolved discussions.

---

*[Source/Layout/MutatorProcedureDefinitionLayout.swift, line 114 at r1](https://reviewable.io:443/reviews/google/blockly-ios/295#-KbGVERyLbxTcZ64NhPx:-KbHh334D07CWho2gFYs:b-896fix) ([raw file](https://github.com/google/blockly-ios/blob/36f14b2ab320d873cc8e81fe1b51fab565ae35dd/Source/Layout/MutatorProcedureDefinitionLayout.swift#L114)):*
<details><summary><i>Previously, RoboErikG wrote…</i></summary><blockquote>

nit ws
</blockquote></details>

Done.

---

*[Source/UI/Views/MutatorProcedureDefinitionView.swift, line 218 at r1](https://reviewable.io:443/reviews/google/blockly-ios/295#-KbGVtnlyG1ZS9MOtqJO:-KbHhHnaizLnYgmEVnMM:b-896fix) ([raw file](https://github.com/google/blockly-ios/blob/36f14b2ab320d873cc8e81fe1b51fab565ae35dd/Source/UI/Views/MutatorProcedureDefinitionView.swift#L218)):*
<details><summary><i>Previously, RoboErikG wrote…</i></summary><blockquote>

nit line length
</blockquote></details>

Done.

---

*[Source/UI/Views/MutatorProcedureDefinitionView.swift, line 232 at r1](https://reviewable.io:443/reviews/google/blockly-ios/295#-KbHNjZJU-3bWpvrNdyP:-KbI6nzoz5qk9mHwU_LB:b-896fix) ([raw file](https://github.com/google/blockly-ios/blob/36f14b2ab320d873cc8e81fe1b51fab565ae35dd/Source/UI/Views/MutatorProcedureDefinitionView.swift#L232)):*
<details><summary><i>Previously, CoryDCode wrote…</i></summary><blockquote>

Not GlobalFont?
</blockquote></details>

Done.

---

*[Source/UI/Views/MutatorProcedureDefinitionView.swift, line 234 at r1](https://reviewable.io:443/reviews/google/blockly-ios/295#-KbHNmZ3KhXmCTSyN5_n:-KbI6oP2ih7wzRHdKVM3:bmlrof0) ([raw file](https://github.com/google/blockly-ios/blob/36f14b2ab320d873cc8e81fe1b51fab565ae35dd/Source/UI/Views/MutatorProcedureDefinitionView.swift#L234)):*
<details><summary><i>Previously, CoryDCode wrote…</i></summary><blockquote>

Could we add a todo to change this from magic numbers?
</blockquote></details>

Commented why these numbers are here. They don't really make sense as configurable values.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/google/blockly-ios/295)*

**Pull request merged**
