### PR TITLE
Fixing the names of the codelab notes.

### PR DESCRIPTION
**Pull request by CoryDCode**
This fixes half of #431 . The second half is fixing the codelab when this gets merged to master.

---
This change is [Reviewable](https://reviewable.io/reviews/google/blockly-ios/451)

### CODE REVIEW

**Comment by vicng** [comment]
Doesn't this break the completed "CodeLab" version? I don't see the filename changes there.

**Comment by vicng** [comment]
I'd recommend testing both projects to make sure nothing breaks. This change also needs to update the actual codelab itself (instructions and screenshots).

**Comment by CoryDCode** [comment]
The sounds are only in one place, and sound_blocks.json is only in the completed version, which is the one I changed. This step (https://codelabs.developers.google.com/codelabs/blockly-ios/#7) is where it gets added in the Starter, and needs to be fixed, but that can't happen until a pull to master. (And is fixed, just unpublished.)

**Comment by vicng** [comment]
https://github.com/google/blockly-ios/tree/develop/Samples/BlocklyCodeLab/BlocklyCodeLab/Resources/Non-Localized/Sounds

https://github.com/google/blockly-ios/tree/develop/Samples/BlocklyCodeLab-Starter/BlocklyCodeLabStarter/Resources/Non-Localized/Sounds

**Comment by vicng** [comment]
Unless our project is setup incorrectly, a test run should've broke, no?

**Comment by CoryDCode** [comment]
Yeah. Weird. Turns out my headphones are broken, and I wasn't paying enough attention.

**Comment by CoryDCode** [comment]
Okay - went back through and tested with both again, and it's working correctly. The codelab (screenshots and sound_blocks.json) is also updated but unpublished.

**Comment by vicng** [comment]
:lgtm:

I'll try to cut a version soon(ish), so you can publish the codelab changes.

---

Review status: 0 of 5 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/google/blockly-ios/451#-:-Kuaf2DmHoLcOMdqhliw:b391fig)*

**Pull request merged**
