### PR TITLE
Fixes for the procedure definition mutator:

### PR DESCRIPTION
**Pull request by vicng**
- no longer jumps around when adding/editing parameters
- bug fix when reordering a parameter
- bug fix when adding a parameter out of view
- changed popover resizing to be less aggressive

---
This change is [Reviewable](https://reviewable.io/reviews/google/blockly-ios/398)

### CODE REVIEW

**Comment by vicng** [comment]
+@corydcode  +@roboerikg 

---

Review status: 0 of 1 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/google/blockly-ios/398#-:-Kjzhlx7NwL3bIPz8z1q:b804esr)*

**Comment by CoryDCode** [comment]
Review status: 0 of 1 files reviewed at latest revision, 2 unresolved discussions.

---

*[Sources/UI/Views/MutatorProcedureDefinitionView.swift, line 426 at r1](https://reviewable.io:443/reviews/google/blockly-ios/398#-KkC7aOkgW5nMYOTkKKy:-KkC7aOlfhx0jDk2mQa0:b6v32sr) ([raw file](https://github.com/google/blockly-ios/blob/eed84c09bf263d40329ae20ebf08f0b6aa37df38/Sources/UI/Views/MutatorProcedureDefinitionView.swift#L426)):*
> ```Swift
> 
>   func updateParameterTextField(_ textField: UITextField) {
>     guard let cell = textField.superview?.superview as? ParameterCellView else {
> ```

Should we move the gesture recognizer to the ParameterCellView? superview?.superview seems fragile.

Alternately, maybe an auxiliary function that finds the parent that's a cell view in case the hierarchy changes for here and below?

---

*[Sources/UI/Views/MutatorProcedureDefinitionView.swift, line 488 at r1](https://reviewable.io:443/reviews/google/blockly-ios/398#-KkC82Bq_sAXr0Bpwd0W:-KkC82Bq_sAXr0Bpwd0X:b-dw2ym4) ([raw file](https://github.com/google/blockly-ios/blob/eed84c09bf263d40329ae20ebf08f0b6aa37df38/Sources/UI/Views/MutatorProcedureDefinitionView.swift#L488)):*
> ```Swift
>           configureParametersHeaderView(headerView)
>         }
>       }
> ```

Log an error here? Either we have a "new" cell with text in it, or a negative index, right? I imagine both are worth sanity checking against?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/google/blockly-ios/398)*

**Comment by vicng** [comment]
Review status: 0 of 2 files reviewed at latest revision, 2 unresolved discussions.

---

*[Sources/UI/Views/MutatorProcedureDefinitionView.swift, line 426 at r1](https://reviewable.io:443/reviews/google/blockly-ios/398#-KkC7aOkgW5nMYOTkKKy:-KkDIKwHUrN93zhRxAUr:b-896fix) ([raw file](https://github.com/google/blockly-ios/blob/eed84c09bf263d40329ae20ebf08f0b6aa37df38/Sources/UI/Views/MutatorProcedureDefinitionView.swift#L426)):*
<details><summary><i>Previously, CoryDCode wrote…</i></summary><blockquote>

Should we move the gesture recognizer to the ParameterCellView? superview?.superview seems fragile.

Alternately, maybe an auxiliary function that finds the parent that's a cell view in case the hierarchy changes for here and below?
</blockquote></details>

Done.

---

*[Sources/UI/Views/MutatorProcedureDefinitionView.swift, line 488 at r1](https://reviewable.io:443/reviews/google/blockly-ios/398#-KkC82Bq_sAXr0Bpwd0W:-KkDILTGaAZO4deazdsd:b-896fix) ([raw file](https://github.com/google/blockly-ios/blob/eed84c09bf263d40329ae20ebf08f0b6aa37df38/Sources/UI/Views/MutatorProcedureDefinitionView.swift#L488)):*
<details><summary><i>Previously, CoryDCode wrote…</i></summary><blockquote>

Log an error here? Either we have a "new" cell with text in it, or a negative index, right? I imagine both are worth sanity checking against?
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/google/blockly-ios/398)*

**Comment by CoryDCode** [comment]
:lgtm: Thanks!

---

Review status: 0 of 2 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/google/blockly-ios/398#-:-KkDJjOgvZZmj4LePePR:b-g2a5fb)*

**Pull request merged**
