### PR TITLE
Implemented change events for fields/mutators

### PR DESCRIPTION
**Pull request by vicng**
This change is [Reviewable](https://reviewable.io/reviews/google/blockly-ios/328)

### CODE REVIEW

**Comment by vicng** [comment]
+@corydcode +@roboerikg 

I've decided not to implement variable/procedure events yet. There are still some issues there wrt variable typing and I think that still needs to be fully fleshed out before settling on how events will work for them.

That said, the change events implemented here do not cause state problems (ie. callers without proc blocks, variable blocks without variables defined) and *should* be good for handling local/realtime events.

---

Review status: 0 of 25 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/google/blockly-ios/328#-:-Kf9gPzCleZV8ZDIfV48:b-rrn49x)*

**Comment by RoboErikG** [comment]
Review status: 0 of 25 files reviewed at latest revision, 4 unresolved discussions.

---

*[Source/Layout/BlockLayout.swift, line 159 at r1](https://reviewable.io:443/reviews/google/blockly-ios/328#-KfDWfDSANy5bibf1xF7:-KfDWfDV-lcud2L_m5S8:b3emoj7) ([raw file](https://github.com/google/blockly-ios/blob/6b576c81153667648b7ce600999de194d1112f3f/Source/Layout/BlockLayout.swift#L159)):*
> ```Swift
>     get { return block.inputsInline }
>     set {
>       if block.editable {
> ```

Do you need to check if the value changed or does it only call set if it has for Bools?

---

*[Source/Layout/FieldAngleLayout.swift, line 65 at r1](https://reviewable.io:443/reviews/google/blockly-ios/328#-KfEHJ7viojT3KVLBk0r:-KfEHJ7wFQVQXiDSjHfi:b-u5ritm) ([raw file](https://github.com/google/blockly-ios/blob/6b576c81153667648b7ce600999de194d1112f3f/Source/Layout/FieldAngleLayout.swift#L65)):*
> ```Swift
>    is not a valid integer, `self.fieldAngle` is not updated.
>    */
>   open func updateAngle(fromText text: String) {
> ```

Would this create a new event when you apply an event?

---

*[Source/Layout/MutatorLayout.swift, line 86 at r1](https://reviewable.io:443/reviews/google/blockly-ios/328#-KfEI5dV67DmJzaXszZv:-KfEI5dV67DmJzaXszZw:b3wna5d) ([raw file](https://github.com/google/blockly-ios/blob/6b576c81153667648b7ce600999de194d1112f3f/Source/Layout/MutatorLayout.swift#L86)):*
> ```Swift
>       // Capture values before and after running mutation
>       let oldValue = mutator.toXMLElement().xml
>       try closure()
> ```

If the mutator changes a field will the field's event and this event have the same group id?

---

*[Source/UI/View Controllers/WorkbenchViewController.swift, line 1140 at r1](https://reviewable.io:443/reviews/google/blockly-ios/328#-KfEIvvnQCZk7P3n6qGb:-KfEIvvnQCZk7P3n6qGc:b-m4lwat) ([raw file](https://github.com/google/blockly-ios/blob/6b576c81153667648b7ce600999de194d1112f3f/Source/UI/View Controllers/WorkbenchViewController.swift#L1140)):*
> ```Swift
>    operations) or run backward (`false` for undo operations).
>    */
>   open func update(fromChangeEvent event: ChangeEvent, runForward: Bool) {
> ```

Should you do the disable/enable of events in here so this can be used for applying events from sources other than undo/redo?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/google/blockly-ios/328)*

**Comment by CoryDCode** [comment]
Review status: 0 of 25 files reviewed at latest revision, 5 unresolved discussions.

---

*[Source/Layout/Layout.swift, line 255 at r1](https://reviewable.io:443/reviews/google/blockly-ios/328#-KfI1R82mvtXNcJk49M3:-KfI1R82mvtXNcJk49M4:bsdxc4f) ([raw file](https://github.com/google/blockly-ios/blob/6b576c81153667648b7ce600999de194d1112f3f/Source/Layout/Layout.swift#L255)):*
> ```Swift
>    - returns: The first ancestor of the given `type`, or `nil` if none could be found.
>    */
>   public final func firstAncestor<T>(ofType type: T.Type? = nil) -> T? where T: Layout {
> ```

Hmm. This seems really inefficient. It's probably not a huge worry, but I wonder if it'd be better to just set your (and your childrens') workspace when you get added to one. Being able to call block.workspace is really handy, which seems like it'll cause a lot of O(n) typecast operations really quickly.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/google/blockly-ios/328)*

**Comment by vicng** [comment]
Review status: 0 of 25 files reviewed at latest revision, 5 unresolved discussions.

---

*[Source/Layout/BlockLayout.swift, line 159 at r1](https://reviewable.io:443/reviews/google/blockly-ios/328#-KfDWfDSANy5bibf1xF7:-KfJW1cijzfwq-J6M_nb:b-aousvy) ([raw file](https://github.com/google/blockly-ios/blob/6b576c81153667648b7ce600999de194d1112f3f/Source/Layout/BlockLayout.swift#L159)):*
<details><summary><i>Previously, RoboErikG wrote…</i></summary><blockquote>

Do you need to check if the value changed or does it only call set if it has for Bools?
</blockquote></details>

Ah yes, this was a mistake :)

---

*[Source/Layout/FieldAngleLayout.swift, line 65 at r1](https://reviewable.io:443/reviews/google/blockly-ios/328#-KfEHJ7viojT3KVLBk0r:-KfJWGZVeL_e7qrmzAbm:b-2r01d9) ([raw file](https://github.com/google/blockly-ios/blob/6b576c81153667648b7ce600999de194d1112f3f/Source/Layout/FieldAngleLayout.swift#L65)):*
<details><summary><i>Previously, RoboErikG wrote…</i></summary><blockquote>

Would this create a new event when you apply an event?
</blockquote></details>

It would create one, but all events are disabled when re-applying events, so no events are fired.

---

*[Source/Layout/Layout.swift, line 255 at r1](https://reviewable.io:443/reviews/google/blockly-ios/328#-KfI1R82mvtXNcJk49M3:-KfJWZ8BzxbpB_y7Hzp7:bngvj4j) ([raw file](https://github.com/google/blockly-ios/blob/6b576c81153667648b7ce600999de194d1112f3f/Source/Layout/Layout.swift#L255)):*
<details><summary><i>Previously, CoryDCode wrote…</i></summary><blockquote>

Hmm. This seems really inefficient. It's probably not a huge worry, but I wonder if it'd be better to just set your (and your childrens') workspace when you get added to one. Being able to call block.workspace is really handy, which seems like it'll cause a lot of O(n) typecast operations really quickly.
</blockquote></details>

Hmm, I don't really want to add a ref to Workspace on Block since developers will rely on it being there.

I do see your point that this method could be inefficient if called repeatedly in code where it shouldn't be (like performLayout()). How about limiting its visibility to `internal` as a compromise? Then at least we can call it responsibly when really needed (in this case, just for events).

---

*[Source/Layout/MutatorLayout.swift, line 86 at r1](https://reviewable.io:443/reviews/google/blockly-ios/328#-KfEI5dV67DmJzaXszZv:-KfJTej_S2FFlrhMQ8U_:b-3knvdz) ([raw file](https://github.com/google/blockly-ios/blob/6b576c81153667648b7ce600999de194d1112f3f/Source/Layout/MutatorLayout.swift#L86)):*
<details><summary><i>Previously, RoboErikG wrote…</i></summary><blockquote>

If the mutator changes a field will the field's event and this event have the same group id?
</blockquote></details>

At the moment, no. The next CL tackles grouping.

---

*[Source/UI/View Controllers/WorkbenchViewController.swift, line 1140 at r1](https://reviewable.io:443/reviews/google/blockly-ios/328#-KfEIvvnQCZk7P3n6qGb:-KfJTu1vCXEhoB960VVU:ban1096) ([raw file](https://github.com/google/blockly-ios/blob/6b576c81153667648b7ce600999de194d1112f3f/Source/UI/View Controllers/WorkbenchViewController.swift#L1140)):*
<details><summary><i>Previously, RoboErikG wrote…</i></summary><blockquote>

Should you do the disable/enable of events in here so this can be used for applying events from sources other than undo/redo?
</blockquote></details>

I still need to work through the cases of event echoing.

Ultimately, the goal is to come up with a consistent behavior (whatever that may be) so it can be documented. It's tough tackling all of this at once though, so the safest thing to do right now is to disable events while replaying the event stack and then re-enabling them after.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/google/blockly-ios/328)*

**Comment by RoboErikG** [comment]
:lgtm:  Make sure you write down the design decisions that need review somewhere.

---

Review status: 0 of 25 files reviewed at latest revision, 5 unresolved discussions.

---

*[Source/UI/View Controllers/WorkbenchViewController.swift, line 1140 at r1](https://reviewable.io:443/reviews/google/blockly-ios/328#-KfEIvvnQCZk7P3n6qGb:-KfMrrqJ5xGwJI0fcZ7B:b-iu59rv) ([raw file](https://github.com/google/blockly-ios/blob/6b576c81153667648b7ce600999de194d1112f3f/Source/UI/View Controllers/WorkbenchViewController.swift#L1140)):*
<details><summary><i>Previously, vicng wrote…</i></summary><blockquote>

I still need to work through the cases of event echoing.

Ultimately, the goal is to come up with a consistent behavior (whatever that may be) so it can be documented. It's tough tackling all of this at once though, so the safest thing to do right now is to disable events while replaying the event stack and then re-enabling them after.


</blockquote></details>

Yep, fine to add some TODO's to review these decisions. Try to think about it in terms of APIs and what the developer is allowed to call and in what order.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/google/blockly-ios/328#-:-KfMs3Yh5-X76DZa-Qyf:b5uf0x4)*

**Pull request merged**
