### PR TITLE
Fixing the brief moment where the play button doesn't do anything by …

### PR DESCRIPTION
**Pull request by CoryDCode**
…disabling the button when it won't do anything.

---

This change is [Reviewable](https://reviewable.io/reviews/google/blockly-ios/249)

### CODE REVIEW

**Comment by CoryDCode** [comment]
+@vicng +@roboerikg 

---

Review status: 0 of 2 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/google/blockly-ios/249#-:-KUIkNbiIKpu_zxdtzqD:bneml20)*

**Comment by RoboErikG** [comment]
I'm not sure this is the best UX since it'll prevent the user from cancelling an in flight generation. A better approach would be to just keep track of what state you expect to be in and discard results if the last thing the user did was press stop.

**Comment by CoryDCode** [comment]
I'm not convinced cancelling generation should be allowed. The cancel button should stop the turtle. If the turtle's not running yet, it shouldn't be allowed to be cancelled. Generally, UX allowing "something that hasn't started yet" to be stopped is an odd experience, to me. This state happens when the code generators are being loaded from disk. Say (hypothetically) this load took 3 minutes, rather than less than a second. Allowing the cancel button to be hit would allow a user to toggle back and forth between "playing, but nothing is happening" (while it's loading in the background) and "cancelling." Both buttons would do nothing, and it would not portray the state accurately to the user. Disabling the button indicates "Hey, something's happening here," without allowing the user to hit a button that won't really do anything.

---

Review status: 0 of 2 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/google/blockly-ios/249#-:-KUIlOTVb4VGMFKKMUg2:b-1bebc8)*

**Comment by vicng** [comment]
It might be helpful to A/B test this with a couple of people, to test both UXs.

Right now, the run button controls one process (generate code and then run the turtle). To me, I'd say stopping this entire process would be expected since you don't start each task individually. Part of the problem is that things aren't sequential  ordered on screen -- like maybe the web view should appear below the code generation to indicate it comes after the code gets generated. Also, the web view should probably be grayed out or something while the code is generating, so it's obvious that is what's happening first.

All that said, I think a better UX fix is to demonstrate "pre-loading" of the code generator. Basically we should run an empty request through the service as soon as the view controller is instantiated, so the web view is preloaded into memory (which is what causes the first run to take so long). I've been thinking this practice should be documented and maybe even made into an API method so people are aware it should be done.

---

Review status: 0 of 2 files reviewed at latest revision, 1 unresolved discussion.

---

*[Samples/BlocklySample/Code/TurtleObjCViewController.m, line 319 at r1](https://reviewable.io:443/reviews/google/blockly-ios/249#-KUItKWen4V1kAvEei2S:-KUItKWen4V1kAvEei2T:b-3j6d7c) ([raw file](https://github.com/google/blockly-ios/blob/d1ba8e56bb7ebaac87d3025524fa64097fa60723/Samples/BlocklySample/Code/TurtleObjCViewController.m#L319)):*
> ```objc
>   self.currentlyRunning = true;
>   self.playButton.enabled = YES;
>   [self.playButton setImage:[UIImage imageNamed:@"cancel_button"] forState:UIControlStateNormal];
> ```

We also need to be changing the text of the button to "Stop".

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/google/blockly-ios/249#-:-KUIuIL3ZYMCugXo29JZ:b-ofv5g8)*

**Comment by CoryDCode** [comment]
NOTE: I'm looking into removing the underlying cause, rather than fiddling with this more.

---

Review status: 0 of 2 files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/google/blockly-ios/249#-:-KUOl3zoBXY94i6s81Z7:bi36wa4)*

**Comment by vicng** [comment]
Do you want to submit this before or after refactoring CodeGenerator?

---

Review status: 0 of 2 files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/google/blockly-ios/249#-:-KUP-6KMzWzfqLRJjboG:b-qds8sn)*

**Comment by CoryDCode** [comment]
After. I think that once that's addressed, the issue of "what to do about that one second of disabled button" will turn into "what to do about that .01 second of disabled button," so it won't really matter.

---

Review status: 0 of 2 files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/google/blockly-ios/249#-:-KUP-R2jhyx7iFpW_8cH:b-7x9wld)*

**Comment by CoryDCode** [comment]
Okay, with #257, the generation takes around 0.02 seconds, so I'm going to leave this solution for completeness, but not bother with spinners and such for such a short amount of time.

---

Review status: 0 of 2 files reviewed at latest revision, 1 unresolved discussion.

---

*[Samples/BlocklySample/Code/TurtleObjCViewController.m, line 319 at r1](https://reviewable.io:443/reviews/google/blockly-ios/249#-KUItKWen4V1kAvEei2S:-KUZQfJhTUdEermUfcX8:b-896fix) ([raw file](https://github.com/google/blockly-ios/blob/d1ba8e56bb7ebaac87d3025524fa64097fa60723/Samples/BlocklySample/Code/TurtleObjCViewController.m#L319)):*
<details><summary><i>Previously, vicng wrote…</i></summary>
> We also need to be changing the text of the button to "Stop".
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/google/blockly-ios/249#-:-KUZQhRGSN0PDYgXgtFM:b-6xb5bd)*

**Comment by vicng** [comment]
:lgtm:

---

Review status: 0 of 2 files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/google/blockly-ios/249#-:-KW5C1QpOhCFnQpsfjRw:bnfp4nl)*

**Pull request merged**
