### PR TITLE
Added support for procedure if-return block

### PR DESCRIPTION
**Pull request by vicng**
This change is [Reviewable](https://reviewable.io/reviews/google/blockly-ios/312)

### CODE REVIEW

**Comment by vicng** [comment]
+@corydcode +@roboerikg 



---

Review status: 0 of 7 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/google/blockly-ios/312#-:-Kc4ny5X2b5nX7hYFCCE:bwl73lh)*

**Comment by vicng** [comment]
Oh and just in case you're wondering if code gen is working:



---

Review status: 0 of 7 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/google/blockly-ios/312#-:-Kc4zAloc0PtT6Xp259E:b1g71v7)*

**Comment by RoboErikG** [comment]
I think you've gotten too far into supporting a class of blocks again instead of having individual blocks with custom behavior. I'd like to see more of the logic for this be part of the block instead of trying to generalize ifreturn procedures into the core library.

---

Review status: 0 of 7 files reviewed at latest revision, 3 unresolved discussions.

---

*[Source/Control/ProcedureCoordinator.swift, line 363 at r1](https://reviewable.io:443/reviews/google/blockly-ios/312#-KcKNW12YGDTh_6abI0U:-KcKNW12YGDTh_6abI0V:b5lbyc8) ([raw file](https://github.com/google/blockly-ios/blob/19959aa8867e3ebd22ba9669e80b58dcd7d7974d/Source/Control/ProcedureCoordinator.swift#L363)):*
> ```Swift
>   fileprivate func validateIfReturnBlock(_ block: Block) {
>     guard let blockLayout = block.layout,
>       let mutatorLayout = blockLayout.mutatorLayout as? MutatorProcedureIfReturnLayout else
> ```

Why does this apply to a class instead of to a specific block definition? This seems to assume a lot about a class of blocks instead of letting a specific block handle the change. On web this is an onchange listener that's part of the block definition: https://github.com/google/blockly/blob/f5f6d69d5ef86d92e249054004c39690b0961f61/blocks/procedures.js#L843

---

*[Source/Control/ProcedureCoordinator.swift, line 467 at r1](https://reviewable.io:443/reviews/google/blockly-ios/312#-KcKN4OSGMDMlTSBl_GK:-KcKN4OSGMDMlTSBl_GL:b-go7y36) ([raw file](https://github.com/google/blockly-ios/blob/19959aa8867e3ebd22ba9669e80b58dcd7d7974d/Source/Control/ProcedureCoordinator.swift#L467)):*
> ```Swift
> 
>   fileprivate dynamic func workspaceLayoutCoordinatorDidConnect(_ notification: NSNotification) {
>     if let layoutCoordinator = notification.object as? WorkspaceLayoutCoordinator,
> ```

Can you short circuit return if the root block isn't a function block?

---

*[Source/Control/ProcedureCoordinator.swift, line 475 at r1](https://reviewable.io:443/reviews/google/blockly-ios/312#-KcKN90206xoIo-F6wHP:-KcKN90206xoIo-F6wHQ:blivdej) ([raw file](https://github.com/google/blockly-ios/blob/19959aa8867e3ebd22ba9669e80b58dcd7d7974d/Source/Control/ProcedureCoordinator.swift#L475)):*
> ```Swift
>       // Validate all if/return blocks in the block tree (starting from the superior connection's
>       // source block).
>       let superiorConnection =
> ```

Do you need to start with the superior connection? It seems like only blocks from the inferior down are new to the parent.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/google/blockly-ios/312#-:-KcKOlVceL43h6t5SH4T:b9yfolz)*

**Comment by RoboErikG** [comment]
Per offline discussion, the ProcedureCoordinator is fine, it's just the code that handles specific blocks that I'd like moved over to the Block's mutator or somewhere that can be defined as part of the block.

---

Review status: 0 of 7 files reviewed at latest revision, 3 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/google/blockly-ios/312#-:-KcKT_xfU0TJh7egtxIW:b-isyvy1)*

**Comment by vicng** [comment]
Review status: 0 of 8 files reviewed at latest revision, 3 unresolved discussions.

---

*[Source/Control/ProcedureCoordinator.swift, line 363 at r1](https://reviewable.io:443/reviews/google/blockly-ios/312#-KcKNW12YGDTh_6abI0U:-KcKp41NYrvqMoBH9xF1:b-896fix) ([raw file](https://github.com/google/blockly-ios/blob/19959aa8867e3ebd22ba9669e80b58dcd7d7974d/Source/Control/ProcedureCoordinator.swift#L363)):*
<details><summary><i>Previously, RoboErikG wrote…</i></summary><blockquote>

Why does this apply to a class instead of to a specific block definition? This seems to assume a lot about a class of blocks instead of letting a specific block handle the change. On web this is an onchange listener that's part of the block definition: https://github.com/google/blockly/blob/f5f6d69d5ef86d92e249054004c39690b0961f61/blocks/procedures.js#L843
</blockquote></details>

Done.

---

*[Source/Control/ProcedureCoordinator.swift, line 467 at r1](https://reviewable.io:443/reviews/google/blockly-ios/312#-KcKN4OSGMDMlTSBl_GK:-KcKpCS96kCI9arnZ4um:benjlpu) ([raw file](https://github.com/google/blockly-ios/blob/19959aa8867e3ebd22ba9669e80b58dcd7d7974d/Source/Control/ProcedureCoordinator.swift#L467)):*
<details><summary><i>Previously, RoboErikG wrote…</i></summary><blockquote>

Can you short circuit return if the root block isn't a function block?
</blockquote></details>

No longer applicable.

---

*[Source/Control/ProcedureCoordinator.swift, line 475 at r1](https://reviewable.io:443/reviews/google/blockly-ios/312#-KcKN90206xoIo-F6wHP:-KcKp9-ca4Q-tfGwVN79:benjlpu) ([raw file](https://github.com/google/blockly-ios/blob/19959aa8867e3ebd22ba9669e80b58dcd7d7974d/Source/Control/ProcedureCoordinator.swift#L475)):*
<details><summary><i>Previously, RoboErikG wrote…</i></summary><blockquote>

Do you need to start with the superior connection? It seems like only blocks from the inferior down are new to the parent.
</blockquote></details>

No longer applicable.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/google/blockly-ios/312)*

**Comment by RoboErikG** [comment]
Much happier with this organization. =) :lgtm_strong: 

---

Review status: 0 of 8 files reviewed at latest revision, 6 unresolved discussions.

---

*[Source/Layout/Layout.swift, line 234 at r2](https://reviewable.io:443/reviews/google/blockly-ios/312#-KcKt9E2vq-VexOodHf-:-KcKt9E38bZDIcl5sWFI:b-n0jdrs) ([raw file](https://github.com/google/blockly-ios/blob/30d599e0394626aacb48ab29a7cae48799600e53/Source/Layout/Layout.swift#L234)):*
> ```Swift
>   /**
>    Returns whether this layout is a descendant of a given layout.
>    
> ```

nit ws

---

*[Source/Layout/WorkspaceLayoutCoordinator.swift, line 31 at r2](https://reviewable.io:443/reviews/google/blockly-ios/312#-KcKtn2fhwWvmjm_FsYb:-KcKtn2fhwWvmjm_FsYc:b-n0jdrs) ([raw file](https://github.com/google/blockly-ios/blob/30d599e0394626aacb48ab29a7cae48799600e53/Source/Layout/WorkspaceLayoutCoordinator.swift#L31)):*
> ```Swift
> 
>    The notification's `userInfo` will contain a dictionary of the form:
>    
> ```

nit ws

---

*[Source/Model/MutatorProcedureIfReturn.swift, line 95 at r2](https://reviewable.io:443/reviews/google/blockly-ios/312#-KcKuDriDm1_EOpG0DHE:-KcKuDriDm1_EOpG0DHF:b-n0jdrs) ([raw file](https://github.com/google/blockly-ios/blob/30d599e0394626aacb48ab29a7cae48799600e53/Source/Model/MutatorProcedureIfReturn.swift#L95)):*
> ```Swift
>       inputs.append(input)
>     }
>     
> ```

nit ws

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/google/blockly-ios/312#-:-KcKuG3xRo3ZvKDSagTi:baqi0w4)*

**Comment by vicng** [comment]
Review status: 0 of 8 files reviewed at latest revision, 6 unresolved discussions, all commit checks successful.

---

*[Source/Layout/Layout.swift, line 234 at r2](https://reviewable.io:443/reviews/google/blockly-ios/312#-KcKt9E2vq-VexOodHf-:-KcKzyXJaMuU6eOcF43F:b-896fix) ([raw file](https://github.com/google/blockly-ios/blob/30d599e0394626aacb48ab29a7cae48799600e53/Source/Layout/Layout.swift#L234)):*
<details><summary><i>Previously, RoboErikG wrote…</i></summary><blockquote>

nit ws
</blockquote></details>

Done.

---

*[Source/Layout/WorkspaceLayoutCoordinator.swift, line 31 at r2](https://reviewable.io:443/reviews/google/blockly-ios/312#-KcKtn2fhwWvmjm_FsYb:-KcL-3K18OJJe9jzN9iI:b-896fix) ([raw file](https://github.com/google/blockly-ios/blob/30d599e0394626aacb48ab29a7cae48799600e53/Source/Layout/WorkspaceLayoutCoordinator.swift#L31)):*
<details><summary><i>Previously, RoboErikG wrote…</i></summary><blockquote>

nit ws
</blockquote></details>

Done.

---

*[Source/Model/MutatorProcedureIfReturn.swift, line 95 at r2](https://reviewable.io:443/reviews/google/blockly-ios/312#-KcKuDriDm1_EOpG0DHE:-KcKztiWCeFma4RlfKw5:b-896fix) ([raw file](https://github.com/google/blockly-ios/blob/30d599e0394626aacb48ab29a7cae48799600e53/Source/Model/MutatorProcedureIfReturn.swift#L95)):*
<details><summary><i>Previously, RoboErikG wrote…</i></summary><blockquote>

nit ws
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/google/blockly-ios/312)*

**Pull request merged**
