### PR TITLE
Changed model/layout infrastructure for mutator support

### PR DESCRIPTION
**Pull request by vicng**
This change is [Reviewable](https://reviewable.io/reviews/google/blockly-ios/282)

### CODE REVIEW

**Comment by vicng** [comment]
+@corydcode +@roboerikg 

This CL is missing the code for rendering MutatorLayouts inside a BlockLayout. Will do that in the next CL.

---

Review status: 0 of 20 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/google/blockly-ios/282#-:-KYVnMjwWp7l-zWQAMbc:b-pohgzs)*

**Comment by vicng** [comment]
Bump, in case this got lost

---

Review status: 0 of 20 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/google/blockly-ios/282#-:-KZ3eH7FQYF-Pz6nfGBA:b-q52lsa)*

**Comment by RoboErikG** [comment]
Review status: 0 of 20 files reviewed at latest revision, 4 unresolved discussions.

---

*[Source/Model/Block.swift, line 43 at r1](https://reviewable.io:443/reviews/google/blockly-ios/282#-KZ8-Ba3mWvtTURSDvr5:-KZ8-Ba3mWvtTURSDvr6:b-8r51jp) ([raw file](https://github.com/google/blockly-ios/blob/9f79cc9c51bf1b9196c2ade0645620e7c11fbab8/Source/Model/Block.swift#L43)):*
> ```Swift
>    - parameter shadowBlock: A shadow `Block` that may have been disconnected from the input.
>    */
>   func block(_ block: Block, didRemoveInput input: Input, disconnectedShadowBlock: Block?)
> ```

This assumes a specific mutation and doesn't belong on Block. Mutations are specific to the individual block and the only common API for them should be that a mutation string is generated for xml.

---

*[Source/Model/Block.swift, line 504 at r1](https://reviewable.io:443/reviews/google/blockly-ios/282#-KZ8-kooi0qYsCm8Zq3h:-KZ8-kooi0qYsCm8Zq3i:b-n0jdrs) ([raw file](https://github.com/google/blockly-ios/blob/9f79cc9c51bf1b9196c2ade0645620e7c11fbab8/Source/Model/Block.swift#L504)):*
> ```Swift
>     return valueInput
>   }
>   
> ```

nit ws

---

*[Source/Model/Block.swift, line 534 at r1](https://reviewable.io:443/reviews/google/blockly-ios/282#-KZ80VbfJ-6UWyPHUIOa:-KZ80VbfJ-6UWyPHUIOb:b-pywatl) ([raw file](https://github.com/google/blockly-ios/blob/9f79cc9c51bf1b9196c2ade0645620e7c11fbab8/Source/Model/Block.swift#L534)):*
> ```Swift
>    the input is deleted.
>    */
>   public func removeInput(_ input: Input) {
> ```

A lot of this should be the responsibility of the mutator. In the web UI if there's a shadow on an input that can be removed it currently get deleted as soon as you open the mutator. The developer might want to allow it to be rearranged, or they might want to swap a different one it. Since we don't know, lets not make assumptions here.

---

*[Source/Model/Workspace.swift, line 279 at r1](https://reviewable.io:443/reviews/google/blockly-ios/282#-KZ7zsmQ9HwBvlxpfZIZ:-KZ7zsmQ9HwBvlxpfZI_:b-rlqbhx) ([raw file](https://github.com/google/blockly-ios/blob/9f79cc9c51bf1b9196c2ade0645620e7c11fbab8/Source/Model/Workspace.swift#L279)):*
> ```Swift
> // MARK: - BlockMutationListener Implementation
> 
> extension Workspace: BlockMutationListener {
> ```

I don't think this belongs here. The mutator should be responsible for all of its side effects since it's always a custom implementation for a specific block. The workspace should not be responsible for cleaning up afterwards.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/google/blockly-ios/282)*

**Comment by RoboErikG** [comment]
Sorry for the slow review. I think you make a lot of assumptions about the type of mutation. Please make the mutator responsible for side effects since we don't know what it might mutate.

---

Review status: 0 of 20 files reviewed at latest revision, 4 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/google/blockly-ios/282#-:-KZ81bQqVITC_y4QIQM-:b-7f0tim)*

**Comment by CoryDCode** [comment]
Yeah, sorry - it super did get lost.

---

Review status: 0 of 20 files reviewed at latest revision, 8 unresolved discussions.

---

*[Source/Layout/MutatorLayout.swift, line 47 at r1](https://reviewable.io:443/reviews/google/blockly-ios/282#-KZ8SxSuSa8fyXmZo9L-:-KZ8SxSuSa8fyXmZo9L0:b-n0jdrs) ([raw file](https://github.com/google/blockly-ios/blob/9f79cc9c51bf1b9196c2ade0645620e7c11fbab8/Source/Layout/MutatorLayout.swift#L47)):*
> ```Swift
> 
>    This is where pre-/post- mutation work should be handled.
>  
> ```

nit ws

---

*[Source/Layout/Default/DefaultLayoutFactory.swift, line 186 at r1](https://reviewable.io:443/reviews/google/blockly-ios/282#-KZ83mprthJl912zdqwD:-KZ83mprthJl912zdqwE:b6wh5ag) ([raw file](https://github.com/google/blockly-ios/blob/9f79cc9c51bf1b9196c2ade0645620e7c11fbab8/Source/Layout/Default/DefaultLayoutFactory.swift#L186)):*
> ```Swift
>   }
> 
>   open func makeMutatorLayout(mutator: Mutator, engine: LayoutEngine) throws -> MutatorLayout {
> ```

The functions in this extension should probably be documented.

---

*[Source/Model/Block.swift, line 48 at r1](https://reviewable.io:443/reviews/google/blockly-ios/282#-KZ8T-g_eNT1vEqZDFk9:-KZ8T-g_eNT1vEqZDFkA:b-n0jdrs) ([raw file](https://github.com/google/blockly-ios/blob/9f79cc9c51bf1b9196c2ade0645620e7c11fbab8/Source/Model/Block.swift#L48)):*
> ```Swift
> /**
>  Class that represents a single block.
>  
> ```

nit ws

---

*[Source/Model/Block.swift, line 534 at r1](https://reviewable.io:443/reviews/google/blockly-ios/282#-KZ80VbfJ-6UWyPHUIOa:-KZ8VvRKs8AF9gmA4PvZ:b37kbq6) ([raw file](https://github.com/google/blockly-ios/blob/9f79cc9c51bf1b9196c2ade0645620e7c11fbab8/Source/Model/Block.swift#L534)):*
<details><summary><i>Previously, RoboErikG wrote…</i></summary><blockquote>

A lot of this should be the responsibility of the mutator. In the web UI if there's a shadow on an input that can be removed it currently get deleted as soon as you open the mutator. The developer might want to allow it to be rearranged, or they might want to swap a different one it. Since we don't know, lets not make assumptions here.
</blockquote></details>

Yeah, I tend to agree, here. We'll need some interface to do "make this input go away", but all the auxiliary logic should be on the mutator.

---

*[Source/Model/Mutator.swift, line 35 at r1](https://reviewable.io:443/reviews/google/blockly-ios/282#-KZ8SvDyg4h0wkTGslAG:-KZ8SvDyg4h0wkTGslAH:b-n0jdrs) ([raw file](https://github.com/google/blockly-ios/blob/9f79cc9c51bf1b9196c2ade0645620e7c11fbab8/Source/Model/Mutator.swift#L35)):*
> ```Swift
>   /**
>    Mutates `self.block` based on this mutator's internal state.
>  
> ```

nit ws

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/google/blockly-ios/282#-:-KZ8VmuUyX3n_Bkn47QS:b-a2ds3d)*

**Comment by vicng** [comment]
Review status: 0 of 18 files reviewed at latest revision, 8 unresolved discussions.

---

*[Source/Layout/MutatorLayout.swift, line 47 at r1](https://reviewable.io:443/reviews/google/blockly-ios/282#-KZ8SxSuSa8fyXmZo9L-:-KZNzaXr7OGNxY37sKdH:b-896fix) ([raw file](https://github.com/google/blockly-ios/blob/9f79cc9c51bf1b9196c2ade0645620e7c11fbab8/Source/Layout/MutatorLayout.swift#L47)):*
<details><summary><i>Previously, CoryDCode wrote…</i></summary><blockquote>

nit ws
</blockquote></details>

Done.

---

*[Source/Layout/Default/DefaultLayoutFactory.swift, line 186 at r1](https://reviewable.io:443/reviews/google/blockly-ios/282#-KZ83mprthJl912zdqwD:-KZNzdmdQrONY2FvSnjd:b-khju4b) ([raw file](https://github.com/google/blockly-ios/blob/9f79cc9c51bf1b9196c2ade0645620e7c11fbab8/Source/Layout/Default/DefaultLayoutFactory.swift#L186)):*
<details><summary><i>Previously, CoryDCode wrote…</i></summary><blockquote>

The functions in this extension should probably be documented.
</blockquote></details>

They're documented in the protocol declaration.

---

*[Source/Model/Block.swift, line 43 at r1](https://reviewable.io:443/reviews/google/blockly-ios/282#-KZ8-Ba3mWvtTURSDvr5:-KZO5cXGLq6rfI2pwjKy:b-896fix) ([raw file](https://github.com/google/blockly-ios/blob/9f79cc9c51bf1b9196c2ade0645620e7c11fbab8/Source/Model/Block.swift#L43)):*
<details><summary><i>Previously, RoboErikG wrote…</i></summary><blockquote>

This assumes a specific mutation and doesn't belong on Block. Mutations are specific to the individual block and the only common API for them should be that a mutation string is generated for xml.
</blockquote></details>

Done.

---

*[Source/Model/Block.swift, line 48 at r1](https://reviewable.io:443/reviews/google/blockly-ios/282#-KZ8T-g_eNT1vEqZDFk9:-KZNzoeudhVCVMBMbsqf:b-896fix) ([raw file](https://github.com/google/blockly-ios/blob/9f79cc9c51bf1b9196c2ade0645620e7c11fbab8/Source/Model/Block.swift#L48)):*
<details><summary><i>Previously, CoryDCode wrote…</i></summary><blockquote>

nit ws
</blockquote></details>

Done.

---

*[Source/Model/Block.swift, line 504 at r1](https://reviewable.io:443/reviews/google/blockly-ios/282#-KZ8-kooi0qYsCm8Zq3h:-KZNzsXr4YAcBrCCAHQh:b-896fix) ([raw file](https://github.com/google/blockly-ios/blob/9f79cc9c51bf1b9196c2ade0645620e7c11fbab8/Source/Model/Block.swift#L504)):*
<details><summary><i>Previously, RoboErikG wrote…</i></summary><blockquote>

nit ws
</blockquote></details>

Done.

---

*[Source/Model/Block.swift, line 534 at r1](https://reviewable.io:443/reviews/google/blockly-ios/282#-KZ80VbfJ-6UWyPHUIOa:-KZO-ErYeU2wNyG6m3Wi:b-jcke1c) ([raw file](https://github.com/google/blockly-ios/blob/9f79cc9c51bf1b9196c2ade0645620e7c11fbab8/Source/Model/Block.swift#L534)):*
<details><summary><i>Previously, CoryDCode wrote…</i></summary><blockquote>

Yeah, I tend to agree, here. We'll need some interface to do "make this input go away", but all the auxiliary logic should be on the mutator.
</blockquote></details>

No assumptions have been made. The caller of `removeInput` is responsible for reconnecting disconnected blocks due to calling this method. However, existing connections of this input must be disconnected when this method is called -- the model can go significantly out of sync otherwise.

The web's implementation is very similar to this btw (https://github.com/google/blockly/blob/master/core/block.js#L1243).  Only difference is that the web deletes shadow blocks immediately, while iOS disconnects it.

---

*[Source/Model/Mutator.swift, line 35 at r1](https://reviewable.io:443/reviews/google/blockly-ios/282#-KZ8SvDyg4h0wkTGslAG:-KZO1WGEul0rf5SAdCMQ:b-896fix) ([raw file](https://github.com/google/blockly-ios/blob/9f79cc9c51bf1b9196c2ade0645620e7c11fbab8/Source/Model/Mutator.swift#L35)):*
<details><summary><i>Previously, CoryDCode wrote…</i></summary><blockquote>

nit ws
</blockquote></details>

Done.

---

*[Source/Model/Workspace.swift, line 279 at r1](https://reviewable.io:443/reviews/google/blockly-ios/282#-KZ7zsmQ9HwBvlxpfZIZ:-KZO5a4kJP05oYrJT7BY:b-896fix) ([raw file](https://github.com/google/blockly-ios/blob/9f79cc9c51bf1b9196c2ade0645620e7c11fbab8/Source/Model/Workspace.swift#L279)):*
<details><summary><i>Previously, RoboErikG wrote…</i></summary><blockquote>

I don't think this belongs here. The mutator should be responsible for all of its side effects since it's always a custom implementation for a specific block. The workspace should not be responsible for cleaning up afterwards.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/google/blockly-ios/282)*

**Comment by CoryDCode** [comment]
:lgtm:

---

Review status: 0 of 18 files reviewed at latest revision, 8 unresolved discussions.

---

*[Source/Layout/Default/DefaultLayoutFactory.swift, line 186 at r1](https://reviewable.io:443/reviews/google/blockly-ios/282#-KZ83mprthJl912zdqwD:-KZOHOuRJr21nvRrzb8p:b-2r8nk9) ([raw file](https://github.com/google/blockly-ios/blob/9f79cc9c51bf1b9196c2ade0645620e7c11fbab8/Source/Layout/Default/DefaultLayoutFactory.swift#L186)):*
<details><summary><i>Previously, vicng wrote…</i></summary><blockquote>

They're documented in the protocol declaration.
</blockquote></details>

I'm dumb. Thanks.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/google/blockly-ios/282#-:-KZOHt16g14oAgHiQdZz:bnfp4nl)*

**Pull request merged**
