### PR TITLE
- Converted remaining default block JSON definitions to use message keys

### PR DESCRIPTION
**Pull request by vicng**
- Localized UI specific code
- Fixed bug where editing FieldDate for the first time showed today's date
- Added localization for French

---
This change is [Reviewable](https://reviewable.io/reviews/google/blockly-ios/344)

### CODE REVIEW

**Comment by vicng** [comment]
+@corydcode +@roboerikg 

---

Review status: 0 of 22 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/google/blockly-ios/344#-:-Kga8se-IgdDQvKYGepg:b4ivu6b)*

**Comment by vicng** [comment]
Bump. Hoping to check in a follow up CL after this.

---

Review status: 0 of 22 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/google/blockly-ios/344#-:-Kgq6JDng7BWbuFC3J7m:bd1vdaa)*

**Comment by RoboErikG** [comment]
:lgtm:

---

Review status: 0 of 22 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/google/blockly-ios/344#-:-Kgq7t12ura5PqKpOCXH:bnfp4nl)*

**Comment by CoryDCode** [comment]
:lgtm:

---

Reviewed 23 of 24 files at r1.
Review status: 21 of 22 files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/google/blockly-ios/344#-:-Kgq86x9k-gX_yQRJyYD:bnfp4nl)*

**Pull request merged**
