### PR TITLE
- Added procedure functionality

### PR DESCRIPTION
**Pull request by vicng**
- Added method to NameManager for renaming existing name with new case sensitivty
- Fixed ToolboxCategoryViewController logic for how it was creating variable blocks
- Allowed copied blocks to have their position set immediately on creation

---
This change is [Reviewable](https://reviewable.io/reviews/google/blockly-ios/307)

### CODE REVIEW

**Comment by vicng** [comment]
+@corydcode +@roboerikg 



Note that I still need to implement code generation for procedures and better logic for updating caller block connections when parameters have been re-ordered in the definition blocks.

---

Review status: 0 of 15 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/google/blockly-ios/307#-:-Kbs_Ao18EFLDbXGVh8u:b-izg82m)*

**Comment by CoryDCode** [comment]
Review status: 0 of 15 files reviewed at latest revision, 5 unresolved discussions.

---

*[Source/Control/NameManager.swift, line 177 at r1](https://reviewable.io:443/reviews/google/blockly-ios/307#-Kbuy4tb63gxzqEEeX9D:-Kbuy4tcSseE6fnnD-nt:b-n0jdrs) ([raw file](https://github.com/google/blockly-ios/blob/2742138815c1d7c6bab4b97a20bdbbfa3f187f92/Source/Control/NameManager.swift#L177)):*
> ```Swift
> 
>    Here is an example of this behavior:
>    
> ```

nit ws

---

*[Source/Control/ProcedureCoordinator.swift, line 94 at r1](https://reviewable.io:443/reviews/google/blockly-ios/307#-Kbv3vBUkl3RVi3TKUFL:-Kbv3vBUkl3RVi3TKUFM:b-n0jdrs) ([raw file](https://github.com/google/blockly-ios/blob/2742138815c1d7c6bab4b97a20bdbbfa3f187f92/Source/Control/ProcedureCoordinator.swift#L94)):*
> ```Swift
>    - All parameters used in procedure definition blocks are created as variables inside
>    `workbench.variableNameManager`.
>    
> ```

nit ws

---

*[Source/Control/ProcedureCoordinator.swift, line 352 at r1](https://reviewable.io:443/reviews/google/blockly-ios/307#-Kbve3Iv0d18O7Cpdww6:-Kbve3Iv0d18O7Cpdww7:b-inlwj7) ([raw file](https://github.com/google/blockly-ios/blob/2742138815c1d7c6bab4b97a20bdbbfa3f187f92/Source/Control/ProcedureCoordinator.swift#L352)):*
> ```Swift
>   fileprivate func firstToolboxProcedureLayoutCoordinator() -> WorkspaceLayoutCoordinator? {
>     if let toolboxLayout = workbench?.toolboxCategoryViewController.toolboxLayout {
>       for (i, category) in toolboxLayout.toolbox.categories.enumerated() {
> ```

Why not "for category in toolboxLayout.toolbox.categories"?

---

*[Source/Control/ProcedureCoordinator.swift, line 396 at r1](https://reviewable.io:443/reviews/google/blockly-ios/307#-KbveWVKYhzvQvvt034z:-KbveWVKYhzvQvvt035-:b9h1djt) ([raw file](https://github.com/google/blockly-ios/blob/2742138815c1d7c6bab4b97a20bdbbfa3f187f92/Source/Control/ProcedureCoordinator.swift#L396)):*
> ```Swift
>     }
> 
>     if newProcedureName.trimmingCharacters(in: .whitespaces).isEmpty {
> ```

We need to support loading of empty strings. I think this won't work loading from XML. However, we can disallow it from the UI (we haven't come to that conclusion yet for sure - see https://github.com/google/blockly/issues/902, but probably will make that change.)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/google/blockly-ios/307)*

**Comment by vicng** [comment]
Review status: 0 of 15 files reviewed at latest revision, 5 unresolved discussions.

---

*[Source/Control/NameManager.swift, line 177 at r1](https://reviewable.io:443/reviews/google/blockly-ios/307#-Kbuy4tb63gxzqEEeX9D:-Kbvn-GOeQ_g6IblQblv:b-896fix) ([raw file](https://github.com/google/blockly-ios/blob/2742138815c1d7c6bab4b97a20bdbbfa3f187f92/Source/Control/NameManager.swift#L177)):*
<details><summary><i>Previously, CoryDCode wrote…</i></summary><blockquote>

nit ws
</blockquote></details>

Done.

---

*[Source/Control/NameManager.swift, line 185 at r1](https://reviewable.io:443/reviews/google/blockly-ios/307#-Kbs_3gUyhyWWqiHJcjT-r1-185:-Kbvn-fh0CbFhd4FzRnE:b-896fix) ([raw file](https://github.com/google/blockly-ios/blob/2742138815c1d7c6bab4b97a20bdbbfa3f187f92/Source/Control/NameManager.swift#L185)):*
<details><summary><i>Previously, RoboErikG wrote…</i></summary><blockquote>

s/newName/displayName/
</blockquote></details>

Done.

---

*[Source/Control/ProcedureCoordinator.swift, line 94 at r1](https://reviewable.io:443/reviews/google/blockly-ios/307#-Kbv3vBUkl3RVi3TKUFL:-Kbvpo53CfL_VwqfbBrY:b-896fix) ([raw file](https://github.com/google/blockly-ios/blob/2742138815c1d7c6bab4b97a20bdbbfa3f187f92/Source/Control/ProcedureCoordinator.swift#L94)):*
<details><summary><i>Previously, CoryDCode wrote…</i></summary><blockquote>

nit ws
</blockquote></details>

Done.

---

*[Source/Control/ProcedureCoordinator.swift, line 352 at r1](https://reviewable.io:443/reviews/google/blockly-ios/307#-Kbve3Iv0d18O7Cpdww6:-Kbvq-rCT-MvbweSPfh5:b-s6vub7) ([raw file](https://github.com/google/blockly-ios/blob/2742138815c1d7c6bab4b97a20bdbbfa3f187f92/Source/Control/ProcedureCoordinator.swift#L352)):*
<details><summary><i>Previously, CoryDCode wrote…</i></summary><blockquote>

Why not "for category in toolboxLayout.toolbox.categories"?
</blockquote></details>

The index is needed for the categoryLayoutCoordinators array.

---

*[Source/Control/ProcedureCoordinator.swift, line 396 at r1](https://reviewable.io:443/reviews/google/blockly-ios/307#-KbveWVKYhzvQvvt034z:-KbvrU0qMKnynraOL_6-:b-i5vmzu) ([raw file](https://github.com/google/blockly-ios/blob/2742138815c1d7c6bab4b97a20bdbbfa3f187f92/Source/Control/ProcedureCoordinator.swift#L396)):*
<details><summary><i>Previously, CoryDCode wrote…</i></summary><blockquote>

We need to support loading of empty strings. I think this won't work loading from XML. However, we can disallow it from the UI (we haven't come to that conclusion yet for sure - see https://github.com/google/blockly/issues/902, but probably will make that change.)
</blockquote></details>

Actually, this still supports the loading of an empty function string from XML.

`workspace.loadBlocks(fromXML:...)`builds each Block from XML first and then adds them to the workspace. Only once has the block been added to the workspace does `ProcedureCoordinator` attach itself as a `FieldListener` to definition blocks (which means only changes going forward will enforce non-empty function names).

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/google/blockly-ios/307)*

**Comment by CoryDCode** [comment]
:lgtm:

---

Review status: 0 of 15 files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/google/blockly-ios/307#-:-Kbw-wsJ3sUjJNBpRoZF:bnfp4nl)*

**Pull request merged**
