### PR TITLE
Adding UI for renaming and removing variables to match web.

### PR DESCRIPTION
**Pull request by CoryDCode**
This change is [Reviewable](https://reviewable.io/reviews/google/blockly-ios/278)

### CODE REVIEW

**Comment by CoryDCode** [comment]
+@vicng 

---

Review status: 0 of 7 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/google/blockly-ios/278#-:-KXs14OqC8tpS4yYs5zW:b-ijk5r)*

**Comment by vicng** [comment]
Review status: 0 of 7 files reviewed at latest revision, 12 unresolved discussions.

---

*[Source/Layout/FieldVariableLayout.swift, line 68 at r1](https://reviewable.io:443/reviews/google/blockly-ios/278#-KY0o5HMaEeWW6NAlsHm:-KY0o5HMaEeWW6NAlsHn:b758hq4) ([raw file](https://github.com/google/blockly-ios/blob/81be9653f74a378c46ff056511e08d534a67c6af/Source/Layout/FieldVariableLayout.swift#L68)):*
> ```Swift
>   }
> 
>   internal weak var layoutCoordinator: WorkspaceLayoutCoordinator?
> ```

Add comment to explain what it's used for

---

*[Source/Layout/FieldVariableLayout.swift, line 162 at r1](https://reviewable.io:443/reviews/google/blockly-ios/278#-KY0ukr56nGardZAK25B:-KY0ukr56nGardZAK25C:b9j9fid) ([raw file](https://github.com/google/blockly-ios/blob/81be9653f74a378c46ff056511e08d534a67c6af/Source/Layout/FieldVariableLayout.swift#L162)):*
> ```Swift
>     guard let layoutCoordinator = layoutCoordinator else {
>       // If there is no layoutCoordinator set on the layout, this is the only matching variable.
>       return 1
> ```

This is may be my OCD talking, but this should be 0. (You can't match yourself...the whole premise of match.com would be broken!!)

Or just rename the method to something like "numberOfVariableReferences"

---

*[Source/Layout/WorkspaceLayoutCoordinator.swift, line 638 at r1](https://reviewable.io:443/reviews/google/blockly-ios/278#-KY0qBiM1Eqjkm4Ft8fE:-KY0qBiNx-TyqFtjqgUi:besgyfe) ([raw file](https://github.com/google/blockly-ios/blob/81be9653f74a378c46ff056511e08d534a67c6af/Source/Layout/WorkspaceLayoutCoordinator.swift#L638)):*
> ```Swift
>         }
> 
>         for variableLayout in blockGroupLayout.flattenedLayoutTree(ofType: FieldVariableLayout.self) {
> ```

Formatting

---

*[Source/UI/View Controllers/WorkspaceViewController.swift, line 218 at r1](https://reviewable.io:443/reviews/google/blockly-ios/278#-KY0qKHUk6v8Aa2fwNrr:-KY0qKHUk6v8Aa2fwNrs:bbytmq5) ([raw file](https://github.com/google/blockly-ios/blob/81be9653f74a378c46ff056511e08d534a67c6af/Source/UI/View Controllers/WorkspaceViewController.swift#L218)):*
> ```Swift
>   }
> 
>   public func fieldView(_ fieldView: FieldView, requestedToPresentViewController viewController: UIViewController)
> ```

Line length

---

*[Source/UI/Views/FieldVariableView.swift, line 96 at r1](https://reviewable.io:443/reviews/google/blockly-ios/278#-KY0sdKTysicQzriOAh0:-KY0sdKTysicQzriOAh1:bfdwxcr) ([raw file](https://github.com/google/blockly-ios/blob/81be9653f74a378c46ff056511e08d534a67c6af/Source/UI/Views/FieldVariableView.swift#L96)):*
> ```Swift
>   }
> 
>   fileprivate func renameVariable(fieldVariableLayout: FieldVariableLayout) {
> ```

On second thought, these two methods would read better if they're put in the DropdownOptionsViewControllerDelegate extension (since they're only called from there).

---

*[Source/UI/Views/FieldVariableView.swift, line 100 at r1](https://reviewable.io:443/reviews/google/blockly-ios/278#-KY0tPp1yuR9qmfXVWFz:-KY0tPp1yuR9qmfXVWG-:brhm9yl) ([raw file](https://github.com/google/blockly-ios/blob/81be9653f74a378c46ff056511e08d534a67c6af/Source/UI/Views/FieldVariableView.swift#L100)):*
> ```Swift
>       UIAlertController(title: "Rename '\(fieldVariableLayout.variable)' variables to:",
>         message: "", preferredStyle: .alert)
>     renameView.addTextField { (textField: UITextField!) in
> ```

Simplify to `renameView.addTextField { textField in`

---

*[Source/UI/Views/FieldVariableView.swift, line 101 at r1](https://reviewable.io:443/reviews/google/blockly-ios/278#-KY0xmmUeE8cr5NLDgK2:-KY0xmmUeE8cr5NLDgK3:bxwgxym) ([raw file](https://github.com/google/blockly-ios/blob/81be9653f74a378c46ff056511e08d534a67c6af/Source/UI/Views/FieldVariableView.swift#L101)):*
> ```Swift
>         message: "", preferredStyle: .alert)
>     renameView.addTextField { (textField: UITextField!) in
>       textField.placeholder = fieldVariableLayout.variable
> ```

A few small UX changes:
- Change this from `placeholder` to `text`.
- Set `textField.clearButtonMode = .whileEditing` (for the X button)
- Give the text field focus immediately

---

*[Source/UI/Views/FieldVariableView.swift, line 104 at r1](https://reviewable.io:443/reviews/google/blockly-ios/278#-KY0tlvIWbFnBBYv25RY:-KY0tlvIWbFnBBYv25RZ:b73mas3) ([raw file](https://github.com/google/blockly-ios/blob/81be9653f74a378c46ff056511e08d534a67c6af/Source/UI/Views/FieldVariableView.swift#L104)):*
> ```Swift
>     }
>     renameView.addAction(UIAlertAction(title: "Cancel", style: .default, handler: nil))
>     renameView.addAction(UIAlertAction(title: "Rename", style: .default) { (_: UIAlertAction) in
> ```

Simplify ending to `{ _ in`

---

*[Source/UI/Views/FieldVariableView.swift, line 109 at r1](https://reviewable.io:443/reviews/google/blockly-ios/278#-KY0xb8MnWOgYrZ21_Bn:-KY0xb8MnWOgYrZ21_Bo:b-gd4l40) ([raw file](https://github.com/google/blockly-ios/blob/81be9653f74a378c46ff056511e08d534a67c6af/Source/UI/Views/FieldVariableView.swift#L109)):*
> ```Swift
>         fieldVariableLayout.isValidName(newName) else
>       {
>         return
> ```

As discussed offline, re-spawn the dialog in this case.

---

*[Source/UI/Views/FieldVariableView.swift, line 126 at r1](https://reviewable.io:443/reviews/google/blockly-ios/278#-KY0wIRIq5lja04PskHk:-KY0wIRIq5lja04PskHl:b63oaqr) ([raw file](https://github.com/google/blockly-ios/blob/81be9653f74a378c46ff056511e08d534a67c6af/Source/UI/Views/FieldVariableView.swift#L126)):*
> ```Swift
>       // Otherwise, verify the user intended to remove all instances of this variable.
>       let removeView = UIAlertController(title:
>         "Delete \(variableCount) uses of the '\(fieldVariableLayout.variable)' variable?",
> ```

Add double quotes around the variable name.

---

*[Source/UI/Views/FieldVariableView.swift, line 129 at r1](https://reviewable.io:443/reviews/google/blockly-ios/278#-KY0w1GBkkDkOEguzN7q:-KY0w1GBkkDkOEguzN7r:be9oboe) ([raw file](https://github.com/google/blockly-ios/blob/81be9653f74a378c46ff056511e08d534a67c6af/Source/UI/Views/FieldVariableView.swift#L129)):*
> ```Swift
>         message: "", preferredStyle: .alert)
>       removeView.addAction(UIAlertAction(title: "Cancel", style: .default, handler: nil))
>       removeView.addAction(UIAlertAction(title: "Remove", style: .default) { (_: UIAlertAction) in
> ```

Change ending to`{ _ in`

---

*[Source/UI/Views/FieldVariableView.swift, line 180 at r1](https://reviewable.io:443/reviews/google/blockly-ios/278#-KY0sOAliyAX-51eorGs:-KY0sOAliyAX-51eorGt:bcmg4yr) ([raw file](https://github.com/google/blockly-ios/blob/81be9653f74a378c46ff056511e08d534a67c6af/Source/UI/Views/FieldVariableView.swift#L180)):*
> ```Swift
>     var options = fieldVariableLayout.variables
>     options.append((displayName: "Rename Variable", value: "rename"))
>     options.append((displayName: "Remove Variable", value: "remove"))
> ```

We should probably change this to match web's implementation:

Delete the "x" variable 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/google/blockly-ios/278)*

**Comment by vicng** [comment]
Review status: 0 of 7 files reviewed at latest revision, 12 unresolved discussions.

---

*[Source/UI/Views/FieldVariableView.swift, line 101 at r1](https://reviewable.io:443/reviews/google/blockly-ios/278#-KY0xmmUeE8cr5NLDgK2:-KY0zZ8VUPV3EQv_e-f6:bf3jexi) ([raw file](https://github.com/google/blockly-ios/blob/81be9653f74a378c46ff056511e08d534a67c6af/Source/UI/Views/FieldVariableView.swift#L101)):*
<details><summary><i>Previously, vicng wrote…</i></summary><blockquote>

A few small UX changes:
- Change this from `placeholder` to `text`.
- Set `textField.clearButtonMode = .whileEditing` (for the X button)
- Give the text field focus immediately
</blockquote></details>

Maybe, we should also set the placeholder to something like "Variable name"

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/google/blockly-ios/278)*

**Comment by CoryDCode** [comment]
Review status: 0 of 7 files reviewed at latest revision, 12 unresolved discussions.

---

*[Source/Layout/FieldVariableLayout.swift, line 68 at r1](https://reviewable.io:443/reviews/google/blockly-ios/278#-KY0o5HMaEeWW6NAlsHm:-KYFOqPcrX8Qb3XPymTk:b-896fix) ([raw file](https://github.com/google/blockly-ios/blob/81be9653f74a378c46ff056511e08d534a67c6af/Source/Layout/FieldVariableLayout.swift#L68)):*
<details><summary><i>Previously, vicng wrote…</i></summary><blockquote>

Add comment to explain what it's used for
</blockquote></details>

Done.

---

*[Source/Layout/FieldVariableLayout.swift, line 162 at r1](https://reviewable.io:443/reviews/google/blockly-ios/278#-KY0ukr56nGardZAK25B:-KYFOxJRMBEKpz6eHYuc:b-kvqffh) ([raw file](https://github.com/google/blockly-ios/blob/81be9653f74a378c46ff056511e08d534a67c6af/Source/Layout/FieldVariableLayout.swift#L162)):*
<details><summary><i>Previously, vicng wrote…</i></summary><blockquote>

This is may be my OCD talking, but this should be 0. (You can't match yourself...the whole premise of match.com would be broken!!)

Or just rename the method to something like "numberOfVariableReferences"
</blockquote></details>

We need to message the total number of references, so I think it should include itself. But that name's better, so done.

---

*[Source/Layout/WorkspaceLayoutCoordinator.swift, line 638 at r1](https://reviewable.io:443/reviews/google/blockly-ios/278#-KY0qBiM1Eqjkm4Ft8fE:-KYFPDS2pm163oaOGROw:b-896fix) ([raw file](https://github.com/google/blockly-ios/blob/81be9653f74a378c46ff056511e08d534a67c6af/Source/Layout/WorkspaceLayoutCoordinator.swift#L638)):*
<details><summary><i>Previously, vicng wrote…</i></summary><blockquote>

Formatting
</blockquote></details>

Done.

---

*[Source/UI/View Controllers/WorkspaceViewController.swift, line 218 at r1](https://reviewable.io:443/reviews/google/blockly-ios/278#-KY0qKHUk6v8Aa2fwNrr:-KYFPQyVzBWyhLNLjLrQ:b-896fix) ([raw file](https://github.com/google/blockly-ios/blob/81be9653f74a378c46ff056511e08d534a67c6af/Source/UI/View Controllers/WorkspaceViewController.swift#L218)):*
<details><summary><i>Previously, vicng wrote…</i></summary><blockquote>

Line length
</blockquote></details>

Done.

---

*[Source/UI/Views/FieldVariableView.swift, line 96 at r1](https://reviewable.io:443/reviews/google/blockly-ios/278#-KY0sdKTysicQzriOAh0:-KYGHaOa8pgDhXtsgrrc:b-896fix) ([raw file](https://github.com/google/blockly-ios/blob/81be9653f74a378c46ff056511e08d534a67c6af/Source/UI/Views/FieldVariableView.swift#L96)):*
<details><summary><i>Previously, vicng wrote…</i></summary><blockquote>

On second thought, these two methods would read better if they're put in the DropdownOptionsViewControllerDelegate extension (since they're only called from there).
</blockquote></details>

Done.

---

*[Source/UI/Views/FieldVariableView.swift, line 100 at r1](https://reviewable.io:443/reviews/google/blockly-ios/278#-KY0tPp1yuR9qmfXVWFz:-KYFPYoQ0OyTsKoeFG5O:b-896fix) ([raw file](https://github.com/google/blockly-ios/blob/81be9653f74a378c46ff056511e08d534a67c6af/Source/UI/Views/FieldVariableView.swift#L100)):*
<details><summary><i>Previously, vicng wrote…</i></summary><blockquote>

Simplify to `renameView.addTextField { textField in`
</blockquote></details>

Done.

---

*[Source/UI/Views/FieldVariableView.swift, line 101 at r1](https://reviewable.io:443/reviews/google/blockly-ios/278#-KY0xmmUeE8cr5NLDgK2:-KYGDl4HKOWtJ-zflCRj:b-896fix) ([raw file](https://github.com/google/blockly-ios/blob/81be9653f74a378c46ff056511e08d534a67c6af/Source/UI/Views/FieldVariableView.swift#L101)):*
<details><summary><i>Previously, vicng wrote…</i></summary><blockquote>

Maybe, we should also set the placeholder to something like "Variable name"
</blockquote></details>

Done.

---

*[Source/UI/Views/FieldVariableView.swift, line 104 at r1](https://reviewable.io:443/reviews/google/blockly-ios/278#-KY0tlvIWbFnBBYv25RY:-KYGDs283Arb3ChJs5pt:b-896fix) ([raw file](https://github.com/google/blockly-ios/blob/81be9653f74a378c46ff056511e08d534a67c6af/Source/UI/Views/FieldVariableView.swift#L104)):*
<details><summary><i>Previously, vicng wrote…</i></summary><blockquote>

Simplify ending to `{ _ in`
</blockquote></details>

Done.

---

*[Source/UI/Views/FieldVariableView.swift, line 109 at r1](https://reviewable.io:443/reviews/google/blockly-ios/278#-KY0xb8MnWOgYrZ21_Bn:-KYGIhjgiD0iCYbwB4l4:b-896fix) ([raw file](https://github.com/google/blockly-ios/blob/81be9653f74a378c46ff056511e08d534a67c6af/Source/UI/Views/FieldVariableView.swift#L109)):*
<details><summary><i>Previously, vicng wrote…</i></summary><blockquote>

As discussed offline, re-spawn the dialog in this case.
</blockquote></details>

Done.

---

*[Source/UI/Views/FieldVariableView.swift, line 126 at r1](https://reviewable.io:443/reviews/google/blockly-ios/278#-KY0wIRIq5lja04PskHk:-KYGE88nVsdIovwzXuJU:b-896fix) ([raw file](https://github.com/google/blockly-ios/blob/81be9653f74a378c46ff056511e08d534a67c6af/Source/UI/Views/FieldVariableView.swift#L126)):*
<details><summary><i>Previously, vicng wrote…</i></summary><blockquote>

Add double quotes around the variable name.
</blockquote></details>

Done.

---

*[Source/UI/Views/FieldVariableView.swift, line 129 at r1](https://reviewable.io:443/reviews/google/blockly-ios/278#-KY0w1GBkkDkOEguzN7q:-KYGE8PcgWw7-Fie_gCv:b-896fix) ([raw file](https://github.com/google/blockly-ios/blob/81be9653f74a378c46ff056511e08d534a67c6af/Source/UI/Views/FieldVariableView.swift#L129)):*
<details><summary><i>Previously, vicng wrote…</i></summary><blockquote>

Change ending to`{ _ in`
</blockquote></details>

Done.

---

*[Source/UI/Views/FieldVariableView.swift, line 180 at r1](https://reviewable.io:443/reviews/google/blockly-ios/278#-KY0sOAliyAX-51eorGs:-KYGEU335RXl6z92X9kA:b-896fix) ([raw file](https://github.com/google/blockly-ios/blob/81be9653f74a378c46ff056511e08d534a67c6af/Source/UI/Views/FieldVariableView.swift#L180)):*
<details><summary><i>Previously, vicng wrote…</i></summary><blockquote>

We should probably change this to match web's implementation:

Delete the "x" variable 
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/google/blockly-ios/278)*

**Comment by vicng** [comment]
Review status: 0 of 7 files reviewed at latest revision, 14 unresolved discussions.

---

*[Source/UI/Views/FieldVariableView.swift, line 183 at r2](https://reviewable.io:443/reviews/google/blockly-ios/278#-KYGQ86fEtxzhH3ydRMx:-KYGQ86fER7BwlmPJA4H:be0v8ye) ([raw file](https://github.com/google/blockly-ios/blob/39327212ab347dcb5baf7e90f96de8a9ad8c4f5c/Source/UI/Views/FieldVariableView.swift#L183)):*
> ```Swift
>       textField.clearButtonMode = .whileEditing
>       textField.becomeFirstResponder()
>     }
> ```

Would it be possible to use a non-editable, borderless UITextField to display the error message instead (which follows the variable name)? Then we could colour it red and it'd look like those password errors.

---

*[Source/UI/Views/FieldVariableView.swift, line 191 at r2](https://reviewable.io:443/reviews/google/blockly-ios/278#-KYGPYeY8IBNFkJaUHFA:-KYGPYeYEeMU5ust1Cwy:b6sbagy) ([raw file](https://github.com/google/blockly-ios/blob/39327212ab347dcb5baf7e90f96de8a9ad8c4f5c/Source/UI/Views/FieldVariableView.swift#L191)):*
> ```Swift
>       {
>         self.renameVariable(fieldVariableLayout: fieldVariableLayout,
>                             error: "ERROR: Must specify a name.")
> ```

If you can make the above change, then make this "You can't use an empty variable name."

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/google/blockly-ios/278)*

**Comment by vicng** [comment]
:lgtm:

---

Review status: 0 of 7 files reviewed at latest revision, 14 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/google/blockly-ios/278#-:-KYGhKng9j2YoZjWKpLg:b593vm9)*

**Comment by CoryDCode** [comment]
Review status: 0 of 7 files reviewed at latest revision, 14 unresolved discussions.

---

*[Source/UI/Views/FieldVariableView.swift, line 183 at r2](https://reviewable.io:443/reviews/google/blockly-ios/278#-KYGQ86fEtxzhH3ydRMx:-KYGiuF_PCD5RESx9TMD:b-93ttxe) ([raw file](https://github.com/google/blockly-ios/blob/39327212ab347dcb5baf7e90f96de8a9ad8c4f5c/Source/UI/Views/FieldVariableView.swift#L183)):*
<details><summary><i>Previously, vicng wrote…</i></summary><blockquote>

Would it be possible to use a non-editable, borderless UITextField to display the error message instead (which follows the variable name)? Then we could colour it red and it'd look like those password errors.
</blockquote></details>

Not without changing to a different UI than the alert. We should do this, but it seems like a big enough change that we can wait until after the functionality pass.

---

*[Source/UI/Views/FieldVariableView.swift, line 191 at r2](https://reviewable.io:443/reviews/google/blockly-ios/278#-KYGPYeY8IBNFkJaUHFA:-KYKGnOAEQnIOAXcOAck:bgv2fhg) ([raw file](https://github.com/google/blockly-ios/blob/39327212ab347dcb5baf7e90f96de8a9ad8c4f5c/Source/UI/Views/FieldVariableView.swift#L191)):*
<details><summary><i>Previously, vicng wrote…</i></summary><blockquote>

If you can make the above change, then make this "You can't use an empty variable name."
</blockquote></details>

Improved the messaging here.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/google/blockly-ios/278)*

**Pull request merged**
