### PR TITLE
- Adds custom number pad control for number fields, replacing use of …

### PR DESCRIPTION
**Pull request by vicng**
…default iOS keyboard

- Fixes angle picker to render a higher resolution control

---
This change is [Reviewable](https://reviewable.io/reviews/google/blockly-ios/414)

### CODE REVIEW

**Comment by vicng** [comment]
+@corydcode +@roboerikg 



---

Review status: 0 of 12 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/google/blockly-ios/414#-:-KmEMZRct2TZPc4N2z4r:bf9jw3y)*

**Comment by CoryDCode** [comment]
Review status: 0 of 14 files reviewed at latest revision, 5 unresolved discussions, some commit checks failed.

---

*[Sources/Common/UIPopoverPresentationController+Helper.swift, line 60 at r1](https://reviewable.io:443/reviews/google/blockly-ios/414#-KmSXwVEFrAI3t0vWcDr:-KmSXwVEFrAI3t0vWcDs:bdqlkoy) ([raw file](https://github.com/google/blockly-ios/blob/27dd381c49093609590b8e33b0cacd7e72b015ec/Sources/Common/UIPopoverPresentationController+Helper.swift#L60)):*
> ```Swift
>     // From the arrow directions, figure out which popover direction would fit inside the
>     // container view.
>     for arrowDirection in arrowDirections {
> ```

Why is this a loop? Can't we just do "If (check) permittedDirection = .down, if (check) permittedDirection = .up..."? If not, do we want to return when we find a valid direction, or allow multiple arrow directions?

---

*[Sources/UI/View Controllers/AnglePickerViewController.swift, line 84 at r1](https://reviewable.io:443/reviews/google/blockly-ios/414#-KmSYvpyrWVPEP_3pnSj:-KmSYvpyrWVPEP_3pnSk:bkijmuk) ([raw file](https://github.com/google/blockly-ios/blob/27dd381c49093609590b8e33b0cacd7e72b015ec/Sources/UI/View Controllers/AnglePickerViewController.swift#L84)):*
> ```Swift
>     view.addSubview(anglePicker)
> 
>     preferredContentSize = CGSize(width: 200, height: 200)
> ```

Is this just to make it in-line with the number pad? Should we store these values somewhere?

---

*[Sources/UI/Views/NumberPad.swift, line 47 at r1](https://reviewable.io:443/reviews/google/blockly-ios/414#-KmS_XCMiU0oc6ILTu9P:-KmS_XCMiU0oc6ILTu9Q:bao00vz) ([raw file](https://github.com/google/blockly-ios/blob/27dd381c49093609590b8e33b0cacd7e72b015ec/Sources/UI/Views/NumberPad.swift#L47)):*
> ```Swift
> 
>   /// Button for the "0" value.
>   @IBOutlet public weak var button0: UIButton?
> ```

Would it be terribly annoying to ask to put this into a [UIButton?]?

---

*[Sources/UI/Views/NumberPad.swift, line 295 at r1](https://reviewable.io:443/reviews/google/blockly-ios/414#-KmSa3DYbgkf0rczo8pi:-KmSa3DYbgkf0rczo8pj:b-24cgdr) ([raw file](https://github.com/google/blockly-ios/blob/27dd381c49093609590b8e33b0cacd7e72b015ec/Sources/UI/Views/NumberPad.swift#L295)):*
> ```Swift
>   public func didPressButton(_ button: UIButton) {
>     let buttonText: String
>     if button == button0 {
> ```

Then if this is an array, we can use index(of:) to clean this up.

---

*[Sources/UI/Views/NumberPad.swift, line 354 at r1](https://reviewable.io:443/reviews/google/blockly-ios/414#-KmSaaaXmJKCuthNnWzG:-KmSaaaXmJKCuthNnWzH:byfvyqg) ([raw file](https://github.com/google/blockly-ios/blob/27dd381c49093609590b8e33b0cacd7e72b015ec/Sources/UI/Views/NumberPad.swift#L354)):*
> ```Swift
> 
>     if text.isEmpty && !currentText.isEmpty {
>       // Empty text means the backspace key was pressed. Remove last character.
> ```

Can we change this to a constant string? ie _localizedNumberFormatter.deleteString? Just in case we/someone wants to make this field more complicated? (Also, there's theoretically a failure state where a button is misconfigured and didPressButton returns an empty string in the last else clause, resulting in an unexpected delete.)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/google/blockly-ios/414)*

**Comment by vicng** [comment]
Review status: 0 of 14 files reviewed at latest revision, 5 unresolved discussions.

---

*[Sources/Common/UIPopoverPresentationController+Helper.swift, line 60 at r1](https://reviewable.io:443/reviews/google/blockly-ios/414#-KmSXwVEFrAI3t0vWcDr:-KmSd3l2859xNfroQXLM:b-cbfonh) ([raw file](https://github.com/google/blockly-ios/blob/27dd381c49093609590b8e33b0cacd7e72b015ec/Sources/Common/UIPopoverPresentationController+Helper.swift#L60)):*
<details><summary><i>Previously, CoryDCode wrote…</i></summary><blockquote>

Why is this a loop? Can't we just do "If (check) permittedDirection = .down, if (check) permittedDirection = .up..."? If not, do we want to return when we find a valid direction, or allow multiple arrow directions?
</blockquote></details>

arrowDirections is prioritized in order of which direction we want first.

If no suitable arrow direction could be chosen based on current state, then `permittedArrowDirections` remains unchanged on purpose. This lets the caller determine behavior of the popover.

eg.
popover.permittedArrowDirections = [.up, .down, .left, .right]
popover.bky_prioritizeArrowDirections([.up, .down, .left])

---

*[Sources/UI/View Controllers/AnglePickerViewController.swift, line 84 at r1](https://reviewable.io:443/reviews/google/blockly-ios/414#-KmSYvpyrWVPEP_3pnSj:-KmSeTcJrkV8TwusYxzo:byj34bm) ([raw file](https://github.com/google/blockly-ios/blob/27dd381c49093609590b8e33b0cacd7e72b015ec/Sources/UI/View Controllers/AnglePickerViewController.swift#L84)):*
<details><summary><i>Previously, CoryDCode wrote…</i></summary><blockquote>

Is this just to make it in-line with the number pad? Should we store these values somewhere?
</blockquote></details>

At the moment yes, but I may change this view controller to use an angle picker and num pad, with a tab to switch between the two, so the dimensions would then differ from vanilla `NumberPadController`.

I don't see (200,200) being the default popover size for everything, so going to leave this hardcoded for now.

---

*[Sources/UI/Views/NumberPad.swift, line 47 at r1](https://reviewable.io:443/reviews/google/blockly-ios/414#-KmS_XCMiU0oc6ILTu9P:-KmSfFWfE-YRR4YQRZVj:bhttv54) ([raw file](https://github.com/google/blockly-ios/blob/27dd381c49093609590b8e33b0cacd7e72b015ec/Sources/UI/Views/NumberPad.swift#L47)):*
<details><summary><i>Previously, CoryDCode wrote…</i></summary><blockquote>

Would it be terribly annoying to ask to put this into a [UIButton?]?
</blockquote></details>

These are actually defined as @IBOutlet properties in case someone wants to hook this NumberPad with a .XIB file, instead of using the default implementation.

---

*[Sources/UI/Views/NumberPad.swift, line 295 at r1](https://reviewable.io:443/reviews/google/blockly-ios/414#-KmSa3DYbgkf0rczo8pi:-KmSfRFKKHYryo_OG7yU:b-q64pkt) ([raw file](https://github.com/google/blockly-ios/blob/27dd381c49093609590b8e33b0cacd7e72b015ec/Sources/UI/Views/NumberPad.swift#L295)):*
<details><summary><i>Previously, CoryDCode wrote…</i></summary><blockquote>

Then if this is an array, we can use index(of:) to clean this up.
</blockquote></details>

See above.

---

*[Sources/UI/Views/NumberPad.swift, line 354 at r1](https://reviewable.io:443/reviews/google/blockly-ios/414#-KmSaaaXmJKCuthNnWzG:-KmSgNGm2JqpRNIFtMYg:baehpzl) ([raw file](https://github.com/google/blockly-ios/blob/27dd381c49093609590b8e33b0cacd7e72b015ec/Sources/UI/Views/NumberPad.swift#L354)):*
<details><summary><i>Previously, CoryDCode wrote…</i></summary><blockquote>

Can we change this to a constant string? ie _localizedNumberFormatter.deleteString? Just in case we/someone wants to make this field more complicated? (Also, there's theoretically a failure state where a button is misconfigured and didPressButton returns an empty string in the last else clause, resulting in an unexpected delete.)
</blockquote></details>

This is sort of determined by the UITextField delegate method, which is needed for physical keyboard input. It uses the empty string as the delete key, so I'm sort of carrying that forward.

Fixed the misconfigured button scenario.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/google/blockly-ios/414)*

**Comment by RoboErikG** [comment]
One question, otherwise :lgtm: 

---

Review status: 0 of 14 files reviewed at latest revision, 6 unresolved discussions.

---

*[Sources/UI/Views/NumberPad.swift, line 412 at r2](https://reviewable.io:443/reviews/google/blockly-ios/414#-KmYceZ22Q9sPPn5vn1U:-KmYceZ22Q9sPPn5vn1V:bsso6la) ([raw file](https://github.com/google/blockly-ios/blob/078fa94c5a43b4071b4220391191dbbfb5597a6e/Sources/UI/Views/NumberPad.swift#L412)):*
> ```Swift
>     if offset == 0 && currentText.contains(_localizedNumberFormatter.minusSign) {
>       // Move the cursor position to the end, so nothing is inserted before the minus sign
>       let cursorPosition = textField.endOfDocument
> ```

does this mean if I try to put a number in front of the minus sign it'll go on the end instead? If so, should it just move past the minus sign instead of to the end?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/google/blockly-ios/414#-:-KmYdGcZ4W5phkFdJgTF:b-tykwvl)*

**Comment by CoryDCode** [comment]
Review status: 0 of 14 files reviewed at latest revision, 3 unresolved discussions, all commit checks successful.

---

*[Sources/Common/UIPopoverPresentationController+Helper.swift, line 60 at r1](https://reviewable.io:443/reviews/google/blockly-ios/414#-KmSXwVEFrAI3t0vWcDr:-KmYfOpcQotzHE6nkgOS:brmug9z) ([raw file](https://github.com/google/blockly-ios/blob/27dd381c49093609590b8e33b0cacd7e72b015ec/Sources/Common/UIPopoverPresentationController+Helper.swift#L60)):*
<details><summary><i>Previously, vicng wrote…</i></summary><blockquote>

arrowDirections is prioritized in order of which direction we want first.

If no suitable arrow direction could be chosen based on current state, then `permittedArrowDirections` remains unchanged on purpose. This lets the caller determine behavior of the popover.

eg.
popover.permittedArrowDirections = [.up, .down, .left, .right]
popover.bky_prioritizeArrowDirections([.up, .down, .left])
</blockquote></details>

Ah. I was misunderstanding the reason for this function. Is there a use case for changing the prioritization of these? Will we ever call:

bky_prioritizeArrowDirections([.down, .right, .left])

? Would it be simpler to just pass in whether we're RTL, and make a decision on a static set of priorities?

---

*[Sources/UI/Views/NumberPad.swift, line 47 at r1](https://reviewable.io:443/reviews/google/blockly-ios/414#-KmS_XCMiU0oc6ILTu9P:-KmYgIImb4jLCZff_GBv:b-sis7xw) ([raw file](https://github.com/google/blockly-ios/blob/27dd381c49093609590b8e33b0cacd7e72b015ec/Sources/UI/Views/NumberPad.swift#L47)):*
<details><summary><i>Previously, vicng wrote…</i></summary><blockquote>

These are actually defined as @IBOutlet properties in case someone wants to hook this NumberPad with a .XIB file, instead of using the default implementation.
</blockquote></details>

I'm not wild about that - it makes this file quite a bit longer than it needs to be, for the relatively niche use case of "I want to change how this looks, but nothing about how it behaves." I guess I'm alright with it, though.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/google/blockly-ios/414)*

**Comment by vicng** [comment]
Review status: 0 of 14 files reviewed at latest revision, 3 unresolved discussions.

---

*[Sources/Common/UIPopoverPresentationController+Helper.swift, line 60 at r1](https://reviewable.io:443/reviews/google/blockly-ios/414#-KmSXwVEFrAI3t0vWcDr:-KmavFnG0DcqP63tyqF8:b-kmda64) ([raw file](https://github.com/google/blockly-ios/blob/27dd381c49093609590b8e33b0cacd7e72b015ec/Sources/Common/UIPopoverPresentationController+Helper.swift#L60)):*
<details><summary><i>Previously, CoryDCode wrote…</i></summary><blockquote>

Ah. I was misunderstanding the reason for this function. Is there a use case for changing the prioritization of these? Will we ever call:

bky_prioritizeArrowDirections([.down, .right, .left])

? Would it be simpler to just pass in whether we're RTL, and make a decision on a static set of priorities?
</blockquote></details>

The prioritization is determined based on what's being mutated. For example, an if/else mutator popover ideally should not cover the block, in which case priority would be `[.down, .right, .left]`.

Changed signature for RTL.

---

*[Sources/UI/Views/NumberPad.swift, line 412 at r2](https://reviewable.io:443/reviews/google/blockly-ios/414#-KmYceZ22Q9sPPn5vn1U:-Kmb6yYFmjzl5ywpwkng:b6xo5cs) ([raw file](https://github.com/google/blockly-ios/blob/078fa94c5a43b4071b4220391191dbbfb5597a6e/Sources/UI/Views/NumberPad.swift#L412)):*
<details><summary><i>Previously, RoboErikG wrote…</i></summary><blockquote>

does this mean if I try to put a number in front of the minus sign it'll go on the end instead? If so, should it just move past the minus sign instead of to the end?
</blockquote></details>

UITextField does some magic behind to scenes to account for RTL numbers and I can't seem to figure out how to always insert directly after the minus sign in RTL. For now, this is a compromise that seems to work for both (this should be a rare case anyway).

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/google/blockly-ios/414)*

**Pull request merged**
