### PR TITLE
Updated code generator service method signature to "setRequestBuilder" and changed it to preload the request builder by submitting a dummy code request.

### PR DESCRIPTION
**Pull request by vicng**
This change is [Reviewable](https://reviewable.io/reviews/google/blockly-ios/260)

### CODE REVIEW

**Comment by vicng** [comment]
+@corydcode 

---

Review status: 0 of 4 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/google/blockly-ios/260#-:-KW0LWUIp4vjGdPjDINR:b-q78qn8)*

**Comment by CoryDCode** [comment]
Review status: 0 of 4 files reviewed at latest revision, 1 unresolved discussion.

---

*[Source/Common/CodeGeneratorService.swift, line 43 at r1](https://reviewable.io:443/reviews/google/blockly-ios/260#-KW4oo22U7ngKnVFTUna:-KW4oo22U7ngKnVFTUnb:b-r3yqfc) ([raw file](https://github.com/google/blockly-ios/blob/2eda69d8588a6f075355d4c3e058813740123c71/Source/Common/CodeGeneratorService.swift#L43)):*
> ```Swift
>   /// The code generator service request builder. This must be set before requesting code
>   /// generation.
>   public private(set) var requestBuilder: CodeGeneratorServiceRequestBuilder? = nil
> ```

Why change this to public? It doesn't seem like we're using it that way anywhere.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/google/blockly-ios/260)*

**Comment by vicng** [comment]
Review status: 0 of 4 files reviewed at latest revision, 1 unresolved discussion.

---

*[Source/Common/CodeGeneratorService.swift, line 43 at r1](https://reviewable.io:443/reviews/google/blockly-ios/260#-KW4oo22U7ngKnVFTUna:-KW51uUmf5iJkq7Dip1s:b-5k1ren) ([raw file](https://github.com/google/blockly-ios/blob/2eda69d8588a6f075355d4c3e058813740123c71/Source/Common/CodeGeneratorService.swift#L43)):*
<details><summary><i>Previously, CoryDCode wrote…</i></summary>
> Why change this to public? It doesn't seem like we're using it that way anywhere.
</details>
I figured it makes it easier to reference in an error message as the natural getter to setRequestBuilder.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/google/blockly-ios/260)*

**Comment by CoryDCode** [comment]
After that one thing, :lgtm: 

---

Review status: 0 of 4 files reviewed at latest revision, 1 unresolved discussion.

---

*[Source/Common/CodeGeneratorService.swift, line 43 at r1](https://reviewable.io:443/reviews/google/blockly-ios/260#-KW4oo22U7ngKnVFTUna:-KW53iu1Zx2AozgBJJ7i:bnteh9o) ([raw file](https://github.com/google/blockly-ios/blob/2eda69d8588a6f075355d4c3e058813740123c71/Source/Common/CodeGeneratorService.swift#L43)):*
<details><summary><i>Previously, vicng wrote…</i></summary>
> I figured it makes it easier to reference in an error message as the natural getter to setRequestBuilder.
</details>
I still think it's best to leave private, since it shouldn't be mutated once it's set.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/google/blockly-ios/260#-:-KW53mg2Obe_mnR9Hf8m:bq7jx6k)*

**Comment by vicng** [comment]
Review status: 0 of 4 files reviewed at latest revision, 1 unresolved discussion.

---

*[Source/Common/CodeGeneratorService.swift, line 43 at r1](https://reviewable.io:443/reviews/google/blockly-ios/260#-KW4oo22U7ngKnVFTUna:-KW54vxo6uVtht42PMjR:b-896fix) ([raw file](https://github.com/google/blockly-ios/blob/2eda69d8588a6f075355d4c3e058813740123c71/Source/Common/CodeGeneratorService.swift#L43)):*
<details><summary><i>Previously, CoryDCode wrote…</i></summary>
> I still think it's best to leave private, since it shouldn't be mutated once it's set.
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/google/blockly-ios/260)*

**Pull request merged**
