### PR TITLE
Moving CodeGeneratorServiceRequest internally, and adding functionali…

### PR DESCRIPTION
**Pull request by CoryDCode**
…ty to precache Blockly files, to alleviate first generation taking longer.

---
This change is [Reviewable](https://reviewable.io/reviews/google/blockly-ios/257)

### CODE REVIEW

**Comment by CoryDCode** [comment]
+@roboerikg +@vicng 

---

Review status: 0 of 5 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/google/blockly-ios/257#-:-KUZOoRCGUqkY6VoudAs:b-35tvqg)*

**Comment by RoboErikG** [comment]
Review status: 0 of 5 files reviewed at latest revision, 2 unresolved discussions.

---

*[Samples/BlocklySample/Code/TurtleObjCViewController.m, line 273 at r1](https://reviewable.io:443/reviews/google/blockly-ios/257#-KUco4DAx25wfoonav8l:-KUco4DAx25wfoonav8m:bcavjy6) ([raw file](https://github.com/google/blockly-ios/blob/48ff9e14dc647d8b869b422083d990c26ea776d5/Samples/BlocklySample/Code/TurtleObjCViewController.m#L273)):*
> ```objc
>   } else {
>     // Cancel pending requests
>     [_codeGeneratorService cancelAllRequests];
> ```

Should there be any pending requests if we're not running?

---

*[Samples/BlocklySample/Code/TurtleObjCViewController.m, line 314 at r1](https://reviewable.io:443/reviews/google/blockly-ios/257#-KUcoOT29XHmBUra-BZd:-KUcoOT29XHmBUra-BZe:bia2xs9) ([raw file](https://github.com/google/blockly-ios/blob/48ff9e14dc647d8b869b422083d990c26ea776d5/Samples/BlocklySample/Code/TurtleObjCViewController.m#L314)):*
> ```objc
>   [self addTimestampedText:
>     [NSString stringWithFormat:@"An error occurred:\n\n====ERROR====\n\n%@", error]];
> ```

I think you need to reset

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/google/blockly-ios/257)*

**Comment by CoryDCode** [comment]
Review status: 0 of 5 files reviewed at latest revision, 2 unresolved discussions.

---

*[Samples/BlocklySample/Code/TurtleObjCViewController.m, line 273 at r1](https://reviewable.io:443/reviews/google/blockly-ios/257#-KUco4DAx25wfoonav8l:-KUct5fj2yIZ52FrWHZ6:b-yc8m9u) ([raw file](https://github.com/google/blockly-ios/blob/48ff9e14dc647d8b869b422083d990c26ea776d5/Samples/BlocklySample/Code/TurtleObjCViewController.m#L273)):*
<details><summary><i>Previously, RoboErikG wrote…</i></summary>
> Should there be any pending requests if we're not running?
</details>
Shouldn't be, no.  Removing it seems fine.

---

*[Samples/BlocklySample/Code/TurtleObjCViewController.m, line 314 at r1](https://reviewable.io:443/reviews/google/blockly-ios/257#-KUcoOT29XHmBUra-BZd:-KUctzRnzldNm4Ah_3yd:b-z2jbhv) ([raw file](https://github.com/google/blockly-ios/blob/48ff9e14dc647d8b869b422083d990c26ea776d5/Samples/BlocklySample/Code/TurtleObjCViewController.m#L314)):*
<details><summary><i>Previously, RoboErikG wrote…</i></summary>
> I think you need to reset
</details>
Reset what? The turtle gets reset on a new run, and the play button is getting reset below.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/google/blockly-ios/257)*

**Comment by RoboErikG** [comment]
One more comment, :lgtm_strong: whether you agree or not.

---

Review status: 0 of 5 files reviewed at latest revision, 3 unresolved discussions.

---

*[Samples/BlocklySample/Code/TurtleObjCViewController.m, line 314 at r1](https://reviewable.io:443/reviews/google/blockly-ios/257#-KUcoOT29XHmBUra-BZd:-KUdAUQ3dpIz_0UsKHDN:b-10notr) ([raw file](https://github.com/google/blockly-ios/blob/48ff9e14dc647d8b869b422083d990c26ea776d5/Samples/BlocklySample/Code/TurtleObjCViewController.m#L314)):*
<details><summary><i>Previously, CoryDCode wrote…</i></summary>
> Reset what? The turtle gets reset on a new run, and the play button is getting reset below.
</details>
Sorry, I had started a comment before looking through the code more and forgot half a sentence was still there. Ignore.

---

*[Samples/BlocklySample/Code/TurtleObjCViewController.m, line 318 at r1](https://reviewable.io:443/reviews/google/blockly-ios/257#-KUdA_oAVwJ_RmvkDBIn:-KUdA_oBO5wpnSGgDXet:b-ga7luh) ([raw file](https://github.com/google/blockly-ios/blob/48ff9e14dc647d8b869b422083d990c26ea776d5/Samples/BlocklySample/Code/TurtleObjCViewController.m#L318)):*
> ```objc
> }
> 
> - (void)resetPlayButton {
> ```

Maybe rename resetRequests? It does more than reset the button.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/google/blockly-ios/257#-:-KUdAkm7woMn2CrEJkRe:b-cy81zx)*

**Pull request merged**
