### PR TITLE
Cleaned up documentatino to be more jazzy friendly

### PR DESCRIPTION
**Pull request by vicng**
This change is [Reviewable](https://reviewable.io/reviews/google/blockly-ios/252)

### CODE REVIEW

**Comment by vicng** [comment]
+@corydcode

---

Review status: 0 of 22 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/google/blockly-ios/252#-:-KUPr-FZH49fYkk6AJ4a:b-umrj3w)*

**Comment by CoryDCode** [comment]
Review status: 0 of 22 files reviewed at latest revision, 3 unresolved discussions.

---

*[Source/Common/BlocklyError.swift, line 95 at r1](https://reviewable.io:443/reviews/google/blockly-ios/252#-KUSsKjbzv-OX5XvQvxK:-KUSsKjcxSRb_SnFOUop:bge2h80) ([raw file](https://github.com/google/blockly-ios/blob/22a707471313fc9733066929c43b6f14c52e2a03/Source/Common/BlocklyError.swift#L95)):*
> ```Swift
>   }
> 
>   public required init?(coder aDecoder: NSCoder) {
> ```

Why is the documentation gone, here? Are we just okay that it's undocumented?

---

*[Source/Model/Block.swift, line 34 at r1](https://reviewable.io:443/reviews/google/blockly-ios/252#-KUSuSrz08QA1VE5rFJC:-KUSuSrz08QA1VE5rFJD:b-7z08g5) ([raw file](https://github.com/google/blockly-ios/blob/22a707471313fc9733066929c43b6f14c52e2a03/Source/Model/Block.swift#L34)):*
> ```Swift
>  Class that represents a single block.
>  
>  - note: To create a block programmatically, use a `Block.Builder`.
> ```

So, I get the benefit of the typealias here, but this is weird to me. Block.Builder hyperlinks to later in this file, which hyperlinks to the BlockBuilder class. Would it be worth getting rid of the alias in this class and just referring to it as BlockBuilder?

---

*[Source/Model/Input.swift, line 97 at r1](https://reviewable.io:443/reviews/google/blockly-ios/252#-KUSwTE1tot1_xINnodi:-KUSwTE1tot1_xINnodj:b-q48kkz) ([raw file](https://github.com/google/blockly-ios/blob/22a707471313fc9733066929c43b6f14c52e2a03/Source/Model/Input.swift#L97)):*
> ```Swift
>   /// Builder for creating `Input` instances
>   public typealias Builder = InputBuilder
> ```

If we change Block.Builder, we should change this.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/google/blockly-ios/252)*

**Comment by vicng** [comment]
Review status: 0 of 36 files reviewed at latest revision, 3 unresolved discussions.

---

*[Source/Common/BlocklyError.swift, line 95 at r1](https://reviewable.io:443/reviews/google/blockly-ios/252#-KUSsKjbzv-OX5XvQvxK:-KUT_eNCE-KKSUbvkuGf:b-d0p2q6) ([raw file](https://github.com/google/blockly-ios/blob/22a707471313fc9733066929c43b6f14c52e2a03/Source/Common/BlocklyError.swift#L95)):*
<details><summary><i>Previously, CoryDCode wrote…</i></summary>
> Why is the documentation gone, here? Are we just okay that it's undocumented?
</details>
No reason for users to create a BlocklyError, but we have to keep the required initializer public due to BlocklyError being public. On second thought tho, I should have put the `:nodoc` tag here.

---

*[Source/Model/Block.swift, line 34 at r1](https://reviewable.io:443/reviews/google/blockly-ios/252#-KUSuSrz08QA1VE5rFJC:-KUTRFzNe-wPBfN2HaSr:b-ix6k0k) ([raw file](https://github.com/google/blockly-ios/blob/22a707471313fc9733066929c43b6f14c52e2a03/Source/Model/Block.swift#L34)):*
<details><summary><i>Previously, CoryDCode wrote…</i></summary>
> So, I get the benefit of the typealias here, but this is weird to me. Block.Builder hyperlinks to later in this file, which hyperlinks to the BlockBuilder class. Would it be worth getting rid of the alias in this class and just referring to it as BlockBuilder?
</details>
Yeah, I thought about that too. I like how Block.Builder looks stylistically when you read it, but it does complicates things for documentation/following breadcrumbs. Was 50/50 on keeping it before, but you've tipped the scale to one side now.

Removed.

---

*[Source/Model/Input.swift, line 97 at r1](https://reviewable.io:443/reviews/google/blockly-ios/252#-KUSwTE1tot1_xINnodi:-KUTbdSOad7yAewlxaOs:b-896fix) ([raw file](https://github.com/google/blockly-ios/blob/22a707471313fc9733066929c43b6f14c52e2a03/Source/Model/Input.swift#L97)):*
<details><summary><i>Previously, CoryDCode wrote…</i></summary>
> If we change Block.Builder, we should change this.
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/google/blockly-ios/252)*

**Comment by CoryDCode** [comment]
:lgtm:

---

Review status: 0 of 36 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/google/blockly-ios/252#-:-KUTcR8iwXmhY6usK9Wj:bnfp4nl)*

**Pull request merged**
