### PR TITLE
Moving NameManager to the Layout level, rather than the Model level.

### PR DESCRIPTION
**Pull request by CoryDCode**
This change is [Reviewable](https://reviewable.io/reviews/google/blockly-ios/271)

### CODE REVIEW

**Comment by CoryDCode** [comment]
+@vicng 

---

Review status: 0 of 4 files reviewed at latest revision, 1 unresolved discussion.

---

*[Source/Layout/FieldVariableLayout.swift, line 109 at r1](https://reviewable.io:443/reviews/google/blockly-ios/271#-KXCb6EVxV2lxLrT3l04:-KXCb6EVxV2lxLrT3l05:b-5u4q9w) ([raw file](https://github.com/google/blockly-ios/blob/3809a5f9d4efd92a677ef8e211d223945c8fd628/Source/Layout/FieldVariableLayout.swift#L109)):*
> ```Swift
>     if oldValue != variable {
>       if let nameManager = self.nameManager,
>         !nameManager.containsName(variable) {
> ```

I'd like to message this in the log, because it's probably a developer error if we get to this point. What do you think, +@vicng ?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/google/blockly-ios/271#-:-KXCbGoquat-Xc0L5Equ:b-ijk5r)*

**Comment by vicng** [comment]
Review status: 0 of 4 files reviewed at latest revision, 11 unresolved discussions.

---

*[Source/Layout/FieldVariableLayout.swift, line 48 at r1](https://reviewable.io:443/reviews/google/blockly-ios/271#-KXDUQQDl_nemk0N5l6I:-KXDUQQDl_nemk0N5l6J:bheun39) ([raw file](https://github.com/google/blockly-ios/blob/3809a5f9d4efd92a677ef8e211d223945c8fd628/Source/Layout/FieldVariableLayout.swift#L48)):*
> ```Swift
>   public weak var nameManager: NameManager? {
>     didSet {
>       // Remove this field as a listener from its previous nameManager and then request
> ```

Remove "and then..."

---

*[Source/Layout/FieldVariableLayout.swift, line 50 at r1](https://reviewable.io:443/reviews/google/blockly-ios/271#-KXDUMKWTQSzFaJm4wUF:-KXDUMKXrACjEp7S1Ae3:b74yy5p) ([raw file](https://github.com/google/blockly-ios/blob/3809a5f9d4efd92a677ef8e211d223945c8fd628/Source/Layout/FieldVariableLayout.swift#L50)):*
> ```Swift
>       // Remove this field as a listener from its previous nameManager and then request
>       // to remove the name it was using
>       oldValue?.listeners.remove(self) // Remove
> ```

Remove // Remove

---

*[Source/Layout/WorkspaceLayoutCoordinator.swift, line 47 at r1](https://reviewable.io:443/reviews/google/blockly-ios/271#-KXDXi-m4NUuh7DKPRqE:-KXDXi-m4NUuh7DKPRqF:b-i2kr6h) ([raw file](https://github.com/google/blockly-ios/blob/3809a5f9d4efd92a677ef8e211d223945c8fd628/Source/Layout/WorkspaceLayoutCoordinator.swift#L47)):*
> ```Swift
>       oldValue?.listeners.remove(self)
> 
>       self.workspaceLayout.blockGroupLayouts.forEach {
> ```

Remove `self.`

---

*[Source/Layout/WorkspaceLayoutCoordinator.swift, line 50 at r1](https://reviewable.io:443/reviews/google/blockly-ios/271#-KXDXjKOPPZHN_skN7ns:-KXDXjKOPPZHN_skN7nt:b-i2kr6h) ([raw file](https://github.com/google/blockly-ios/blob/3809a5f9d4efd92a677ef8e211d223945c8fd628/Source/Layout/WorkspaceLayoutCoordinator.swift#L50)):*
> ```Swift
>         $0.blockLayouts.forEach { removeNameManagerFromBlockLayout($0) }
>       }
>       self.workspaceLayout.blockGroupLayouts.forEach {
> ```

Remove `self.`

---

*[Source/Layout/WorkspaceLayoutCoordinator.swift, line 102 at r1](https://reviewable.io:443/reviews/google/blockly-ios/271#-KXDVJI9ndhv-Hu2bEDS:-KXDVJI9ndhv-Hu2bEDT:bsbea8) ([raw file](https://github.com/google/blockly-ios/blob/3809a5f9d4efd92a677ef8e211d223945c8fd628/Source/Layout/WorkspaceLayoutCoordinator.swift#L102)):*
> ```Swift
>     workspaceLayout.workspace.listeners.remove(self)
>     if let nameManager = variableNameManager {
>       nameManager.listeners.remove(self)
> ```

Simplify to `variableNameManager?.listeners.remove(self)`

---

*[Source/Layout/WorkspaceLayoutCoordinator.swift, line 583 at r1](https://reviewable.io:443/reviews/google/blockly-ios/271#-KXDVrnoXV6y8XMo71FD:-KXDVrnoXV6y8XMo71FE:b-2k6d08) ([raw file](https://github.com/google/blockly-ios/blob/3809a5f9d4efd92a677ef8e211d223945c8fd628/Source/Layout/WorkspaceLayoutCoordinator.swift#L583)):*
> ```Swift
> 
>   /**
>    For all `FieldVariable` instances under a given `Block`, set their `nameManager` property to a
> ```

Update doc.

---

*[Source/Layout/WorkspaceLayoutCoordinator.swift, line 591 at r1](https://reviewable.io:443/reviews/google/blockly-ios/271#-KXDVWmscBpUhlyo3-2Q:-KXDVWmscBpUhlyo3-2R:b9z93iy) ([raw file](https://github.com/google/blockly-ios/blob/3809a5f9d4efd92a677ef8e211d223945c8fd628/Source/Layout/WorkspaceLayoutCoordinator.swift#L591)):*
> ```Swift
>   fileprivate func addNameManager(_ nameManager: NameManager?,
>                                   toBlockLayout blockLayout: BlockLayout) {
>     blockLayout.inputLayouts.forEach { $0.fieldLayouts.forEach {
> ```

Move `$0.fieldLayouts.forEach` to its own line.

---

*[Source/Layout/WorkspaceLayoutCoordinator.swift, line 599 at r1](https://reviewable.io:443/reviews/google/blockly-ios/271#-KXDVsxp9E4giiLg6BVO:-KXDVsxq98qDAiP2I697:b-2k6d08) ([raw file](https://github.com/google/blockly-ios/blob/3809a5f9d4efd92a677ef8e211d223945c8fd628/Source/Layout/WorkspaceLayoutCoordinator.swift#L599)):*
> ```Swift
> 
>   /**
>    Sets the `nameManager` for all `FieldVariable` instances under the given `Block` to `nil`.
> ```

Update doc.

---

*[Source/Layout/WorkspaceLayoutCoordinator.swift, line 604 at r1](https://reviewable.io:443/reviews/google/blockly-ios/271#-KXDVc6rCZyqllYkt2Ll:-KXDVc6rCZyqllYkt2Lm:b9z93iy) ([raw file](https://github.com/google/blockly-ios/blob/3809a5f9d4efd92a677ef8e211d223945c8fd628/Source/Layout/WorkspaceLayoutCoordinator.swift#L604)):*
> ```Swift
>    */
>   fileprivate func removeNameManagerFromBlockLayout(_ blockLayout: BlockLayout) {
>     blockLayout.inputLayouts.forEach { $0.fieldLayouts.forEach {
> ```

Move `$0.fieldLayouts.forEach` to its own line.

---

*[Source/Model/FieldVariable.swift, line 26 at r1](https://reviewable.io:443/reviews/google/blockly-ios/271#-KXDW9oDV8fS_rdx4OXt:-KXDW9oDV8fS_rdx4OXu:b-hlau95) ([raw file](https://github.com/google/blockly-ios/blob/3809a5f9d4efd92a677ef8e211d223945c8fd628/Source/Model/FieldVariable.swift#L26)):*
> ```Swift
> 
>   /// The variable in this field
>   public internal(set) var variable: String {
> ```

I think we should have an explicit method for setting the variable, so we can throw an error in the case of an empty string.

In this case, this property should be a `private(set)`.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/google/blockly-ios/271)*

**Comment by CoryDCode** [comment]
Review status: 0 of 6 files reviewed at latest revision, 11 unresolved discussions.

---

*[Source/Layout/FieldVariableLayout.swift, line 48 at r1](https://reviewable.io:443/reviews/google/blockly-ios/271#-KXDUQQDl_nemk0N5l6I:-KXlL2hywtQzJbgdls-r:b-896fix) ([raw file](https://github.com/google/blockly-ios/blob/3809a5f9d4efd92a677ef8e211d223945c8fd628/Source/Layout/FieldVariableLayout.swift#L48)):*
<details><summary><i>Previously, vicng wrote…</i></summary>
> Remove "and then..."
</details>
Done.

---

*[Source/Layout/FieldVariableLayout.swift, line 50 at r1](https://reviewable.io:443/reviews/google/blockly-ios/271#-KXDUMKWTQSzFaJm4wUF:-KXlL4g1y_ycJLc2mFyY:b-896fix) ([raw file](https://github.com/google/blockly-ios/blob/3809a5f9d4efd92a677ef8e211d223945c8fd628/Source/Layout/FieldVariableLayout.swift#L50)):*
<details><summary><i>Previously, vicng wrote…</i></summary>
> Remove // Remove
</details>
Done.

---

*[Source/Layout/WorkspaceLayoutCoordinator.swift, line 47 at r1](https://reviewable.io:443/reviews/google/blockly-ios/271#-KXDXi-m4NUuh7DKPRqE:-KXlLC-f9otZ7Av8pk9X:b-896fix) ([raw file](https://github.com/google/blockly-ios/blob/3809a5f9d4efd92a677ef8e211d223945c8fd628/Source/Layout/WorkspaceLayoutCoordinator.swift#L47)):*
<details><summary><i>Previously, vicng wrote…</i></summary>
> Remove `self.`
</details>
Done.

---

*[Source/Layout/WorkspaceLayoutCoordinator.swift, line 50 at r1](https://reviewable.io:443/reviews/google/blockly-ios/271#-KXDXjKOPPZHN_skN7ns:-KXlLCRWa2uTlkZ0PDcu:b-896fix) ([raw file](https://github.com/google/blockly-ios/blob/3809a5f9d4efd92a677ef8e211d223945c8fd628/Source/Layout/WorkspaceLayoutCoordinator.swift#L50)):*
<details><summary><i>Previously, vicng wrote…</i></summary>
> Remove `self.`
</details>
Done.

---

*[Source/Layout/WorkspaceLayoutCoordinator.swift, line 102 at r1](https://reviewable.io:443/reviews/google/blockly-ios/271#-KXDVJI9ndhv-Hu2bEDS:-KXlLOyyc9v3OEY9gnNw:b-896fix) ([raw file](https://github.com/google/blockly-ios/blob/3809a5f9d4efd92a677ef8e211d223945c8fd628/Source/Layout/WorkspaceLayoutCoordinator.swift#L102)):*
<details><summary><i>Previously, vicng wrote…</i></summary>
> Simplify to `variableNameManager?.listeners.remove(self)`
</details>
Done.

---

*[Source/Layout/WorkspaceLayoutCoordinator.swift, line 583 at r1](https://reviewable.io:443/reviews/google/blockly-ios/271#-KXDVrnoXV6y8XMo71FD:-KXlPs8Irc_cSzhslYdk:b-896fix) ([raw file](https://github.com/google/blockly-ios/blob/3809a5f9d4efd92a677ef8e211d223945c8fd628/Source/Layout/WorkspaceLayoutCoordinator.swift#L583)):*
<details><summary><i>Previously, vicng wrote…</i></summary>
> Update doc.
</details>
Done.

---

*[Source/Layout/WorkspaceLayoutCoordinator.swift, line 591 at r1](https://reviewable.io:443/reviews/google/blockly-ios/271#-KXDVWmscBpUhlyo3-2Q:-KXlPzRTe1HIscMX5kaE:b-896fix) ([raw file](https://github.com/google/blockly-ios/blob/3809a5f9d4efd92a677ef8e211d223945c8fd628/Source/Layout/WorkspaceLayoutCoordinator.swift#L591)):*
<details><summary><i>Previously, vicng wrote…</i></summary>
> Move `$0.fieldLayouts.forEach` to its own line.
</details>
Done.

---

*[Source/Layout/WorkspaceLayoutCoordinator.swift, line 599 at r1](https://reviewable.io:443/reviews/google/blockly-ios/271#-KXDVsxp9E4giiLg6BVO:-KXlQ2LIIPNW1VfUOOTk:b-896fix) ([raw file](https://github.com/google/blockly-ios/blob/3809a5f9d4efd92a677ef8e211d223945c8fd628/Source/Layout/WorkspaceLayoutCoordinator.swift#L599)):*
<details><summary><i>Previously, vicng wrote…</i></summary>
> Update doc.
</details>
Done.

---

*[Source/Layout/WorkspaceLayoutCoordinator.swift, line 604 at r1](https://reviewable.io:443/reviews/google/blockly-ios/271#-KXDVc6rCZyqllYkt2Ll:-KXlQ2yy7l23pYGuPzAA:b-896fix) ([raw file](https://github.com/google/blockly-ios/blob/3809a5f9d4efd92a677ef8e211d223945c8fd628/Source/Layout/WorkspaceLayoutCoordinator.swift#L604)):*
<details><summary><i>Previously, vicng wrote…</i></summary>
> Move `$0.fieldLayouts.forEach` to its own line.
</details>
Done.

---

*[Source/Model/FieldVariable.swift, line 26 at r1](https://reviewable.io:443/reviews/google/blockly-ios/271#-KXDW9oDV8fS_rdx4OXt:-KXlpxG4_AkOyp2rKpPp:b-896fix) ([raw file](https://github.com/google/blockly-ios/blob/3809a5f9d4efd92a677ef8e211d223945c8fd628/Source/Model/FieldVariable.swift#L26)):*
<details><summary><i>Previously, vicng wrote…</i></summary>
> I think we should have an explicit method for setting the variable, so we can throw an error in the case of an empty string.
> 
> In this case, this property should be a `private(set)`.
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/google/blockly-ios/271)*

**Comment by vicng** [comment]
Review status: 0 of 6 files reviewed at latest revision, 17 unresolved discussions.

---

*[Source/Layout/FieldVariableLayout.swift, line 109 at r1](https://reviewable.io:443/reviews/google/blockly-ios/271#-KXCb6EVxV2lxLrT3l04:-KXmDTVSW7yQ3fJUcvvQ:brikt6y) ([raw file](https://github.com/google/blockly-ios/blob/3809a5f9d4efd92a677ef8e211d223945c8fd628/Source/Layout/FieldVariableLayout.swift#L109)):*
<details><summary><i>Previously, CoryDCode wrote…</i></summary><blockquote>

I'd like to message this in the log, because it's probably a developer error if we get to this point. What do you think, +@vicng ?
</blockquote></details>

Oops, missed this the first time. Yes, log this as bky_assertionFailure().

---

*[Source/Layout/FieldVariableLayout.swift, line 102 at r2](https://reviewable.io:443/reviews/google/blockly-ios/271#-KXmFNvFTdz3XXvIAATc:-KXmFNvFTdz3XXvIAATd:bck5fnf) ([raw file](https://github.com/google/blockly-ios/blob/6782514fbcffff66ffca2e73d1297e8026220375/Source/Layout/FieldVariableLayout.swift#L102)):*
> ```Swift
>    - parameter variable: The value used to update `self.fieldVariable.variable`.
>    */
>   open func changeToVariable(_ variable: String) {
> ```

Maybe the method name should be changed to "changeToExistingVariable(:)" -- it might make things clearer from a caller's perspective.

---

*[Source/Layout/WorkspaceLayoutCoordinator.swift, line 585 at r2](https://reviewable.io:443/reviews/google/blockly-ios/271#-KXmEi51otm1F11z3I2b:-KXmEi52eHbXcK6XRKK2:b-8nnzta) ([raw file](https://github.com/google/blockly-ios/blob/6782514fbcffff66ffca2e73d1297e8026220375/Source/Layout/WorkspaceLayoutCoordinator.swift#L585)):*
> ```Swift
> 
>    - parameter nameManager: The `NameManager` to set
>    - parameter block: The `BlockLayout`
> ```

blockLayout

---

*[Source/Layout/WorkspaceLayoutCoordinator.swift, line 602 at r2](https://reviewable.io:443/reviews/google/blockly-ios/271#-KXmErdIiqkCPfJ1Qobz:-KXmErdIiqkCPfJ1Qoc-:b-8nnzta) ([raw file](https://github.com/google/blockly-ios/blob/6782514fbcffff66ffca2e73d1297e8026220375/Source/Layout/WorkspaceLayoutCoordinator.swift#L602)):*
> ```Swift
>    `nil`.
> 
>    - parameter block: The `BlockLayout`
> ```

blockLayout

---

*[Source/Model/FieldVariable.swift, line 69 at r2](https://reviewable.io:443/reviews/google/blockly-ios/271#-KXmCW0CfTmM5oxHoa1D:-KXmCW0CfTmM5oxHoa1E:bpv7zhj) ([raw file](https://github.com/google/blockly-ios/blob/6782514fbcffff66ffca2e73d1297e8026220375/Source/Model/FieldVariable.swift#L69)):*
> ```Swift
>    - parameter name: The `String` to check.
>    */
>   public func isValidName(_ name: String) -> Bool {
> ```

Add tests for these two methods.

---

*[Source/Model/FieldVariable.swift, line 84 at r2](https://reviewable.io:443/reviews/google/blockly-ios/271#-KXmCEG2UJLmlQfg5jGz:-KXmCEG2UJLmlQfg5jH-:be24xgr) ([raw file](https://github.com/google/blockly-ios/blob/6782514fbcffff66ffca2e73d1297e8026220375/Source/Model/FieldVariable.swift#L84)):*
> ```Swift
>     guard isValidName(name) else {
>       throw BlocklyError(.illegalArgument, "Cannot set a variable name to an empty string. Call" +
>         " isValidName to validate name before setting it.")
> ```

"isValidName(:)"

---

*[Source/UI/Views/FieldVariableView.swift, line 174 at r2](https://reviewable.io:443/reviews/google/blockly-ios/271#-KXmFbMbpM0HrvgXPE4C:-KXmFbMbpM0HrvgXPE4D:bmq170d) ([raw file](https://github.com/google/blockly-ios/blob/6782514fbcffff66ffca2e73d1297e8026220375/Source/UI/Views/FieldVariableView.swift#L174)):*
> ```Swift
>   }
> }
> ```

Add:

```
// MARK: - VariableNameViewControllerDelegate Implementation
```

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/google/blockly-ios/271)*

**Comment by CoryDCode** [comment]
Review status: 0 of 8 files reviewed at latest revision, 17 unresolved discussions.

---

*[Source/Layout/FieldVariableLayout.swift, line 109 at r1](https://reviewable.io:443/reviews/google/blockly-ios/271#-KXCb6EVxV2lxLrT3l04:-KXmIXqIkk8DzvQKz0S_:b-896fix) ([raw file](https://github.com/google/blockly-ios/blob/3809a5f9d4efd92a677ef8e211d223945c8fd628/Source/Layout/FieldVariableLayout.swift#L109)):*
<details><summary><i>Previously, vicng wrote…</i></summary>
> Oops, missed this the first time. Yes, log this as bky_assertionFailure().
</details>
Done.

---

*[Source/Layout/FieldVariableLayout.swift, line 102 at r2](https://reviewable.io:443/reviews/google/blockly-ios/271#-KXmFNvFTdz3XXvIAATc:-KXmINbmKRuNg4Cj2kDx:bkoke9u) ([raw file](https://github.com/google/blockly-ios/blob/6782514fbcffff66ffca2e73d1297e8026220375/Source/Layout/FieldVariableLayout.swift#L102)):*
<details><summary><i>Previously, vicng wrote…</i></summary>
> Maybe the method name should be changed to "changeToExistingVariable(:)" -- it might make things clearer from a caller's perspective.
</details>
I like it. Done.

---

*[Source/Layout/WorkspaceLayoutCoordinator.swift, line 585 at r2](https://reviewable.io:443/reviews/google/blockly-ios/271#-KXmEi51otm1F11z3I2b:-KXmIbuEpfC4Y-quVffN:b-896fix) ([raw file](https://github.com/google/blockly-ios/blob/6782514fbcffff66ffca2e73d1297e8026220375/Source/Layout/WorkspaceLayoutCoordinator.swift#L585)):*
<details><summary><i>Previously, vicng wrote…</i></summary>
> blockLayout
</details>
Done.

---

*[Source/Layout/WorkspaceLayoutCoordinator.swift, line 602 at r2](https://reviewable.io:443/reviews/google/blockly-ios/271#-KXmErdIiqkCPfJ1Qobz:-KXmIh2HXh_A15_pbEZy:b-896fix) ([raw file](https://github.com/google/blockly-ios/blob/6782514fbcffff66ffca2e73d1297e8026220375/Source/Layout/WorkspaceLayoutCoordinator.swift#L602)):*
<details><summary><i>Previously, vicng wrote…</i></summary>
> blockLayout
</details>
Done.

---

*[Source/Model/FieldVariable.swift, line 69 at r2](https://reviewable.io:443/reviews/google/blockly-ios/271#-KXmCW0CfTmM5oxHoa1D:-KXn72lQuKG1Nbrb9Ibl:b-896fix) ([raw file](https://github.com/google/blockly-ios/blob/6782514fbcffff66ffca2e73d1297e8026220375/Source/Model/FieldVariable.swift#L69)):*
<details><summary><i>Previously, vicng wrote…</i></summary>
> Add tests for these two methods.
</details>
Done.

---

*[Source/Model/FieldVariable.swift, line 84 at r2](https://reviewable.io:443/reviews/google/blockly-ios/271#-KXmCEG2UJLmlQfg5jGz:-KXmInM07kVeZC8LpEep:b-896fix) ([raw file](https://github.com/google/blockly-ios/blob/6782514fbcffff66ffca2e73d1297e8026220375/Source/Model/FieldVariable.swift#L84)):*
<details><summary><i>Previously, vicng wrote…</i></summary>
> "isValidName(:)"
</details>
Done.

---

*[Source/UI/Views/FieldVariableView.swift, line 174 at r2](https://reviewable.io:443/reviews/google/blockly-ios/271#-KXmFbMbpM0HrvgXPE4C:-KXmIrXRnvdjbachswt2:b-896fix) ([raw file](https://github.com/google/blockly-ios/blob/6782514fbcffff66ffca2e73d1297e8026220375/Source/UI/Views/FieldVariableView.swift#L174)):*
<details><summary><i>Previously, vicng wrote…</i></summary>
> Add:
> 
> ```
> // MARK: - VariableNameViewControllerDelegate Implementation
> ```
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/google/blockly-ios/271)*

**Comment by vicng** [comment]
:lgtm:

---

Review status: 0 of 8 files reviewed at latest revision, 16 unresolved discussions.

---

*[Source/Model/FieldVariable.swift, line 84 at r3](https://reviewable.io:443/reviews/google/blockly-ios/271#-KXr9Q47P6iYtw3cNk0J:-KXr9Q47P6iYtw3cNk0K:b-qacwif) ([raw file](https://github.com/google/blockly-ios/blob/ec0d2364485e8143c6ad49f6ee998621fc45eca3/Source/Model/FieldVariable.swift#L84)):*
> ```Swift
>     guard FieldVariable.isValidName(name) else {
>       throw BlocklyError(.illegalArgument, "Cannot set a variable name to an empty string. Call" +
>         " isValidName(:) to validate name before setting it.")
> ```

FieldVariable.isValidName(:) 

---

*[Tests/Source/Model/FieldVariableTest.swift, line 23 at r3](https://reviewable.io:443/reviews/google/blockly-ios/271#-KXr9ZRgrLzkhx62R-ZY:-KXr9ZRgrLzkhx62R-ZZ:b-p8srmc) ([raw file](https://github.com/google/blockly-ios/blob/ec0d2364485e8143c6ad49f6ee998621fc45eca3/Tests/Source/Model/FieldVariableTest.swift#L23)):*
> ```Swift
>   // MARK: - Internal static methods
> 
>   func testParseDate_validNameChange() {
> ```

Fix test method name

---

*[Tests/Source/Model/FieldVariableTest.swift, line 30 at r3](https://reviewable.io:443/reviews/google/blockly-ios/271#-KXr9_sLZxQYDFRxgH2t:-KXr9_sLZxQYDFRxgH2u:bqujbyh) ([raw file](https://github.com/google/blockly-ios/blob/ec0d2364485e8143c6ad49f6ee998621fc45eca3/Tests/Source/Model/FieldVariableTest.swift#L30)):*
> ```Swift
>   }
> 
>   func testParseDate_invalidNameChange() {
> ```

Here too

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/google/blockly-ios/271#-:-KXr9hFB6UQVqiZdDxhx:bnfp4nl)*

**Comment by CoryDCode** [comment]
Review status: 0 of 8 files reviewed at latest revision, 16 unresolved discussions.

---

*[Source/Model/FieldVariable.swift, line 84 at r3](https://reviewable.io:443/reviews/google/blockly-ios/271#-KXr9Q47P6iYtw3cNk0J:-KXrDzlWDZqnxSuFgU6P:b-896fix) ([raw file](https://github.com/google/blockly-ios/blob/ec0d2364485e8143c6ad49f6ee998621fc45eca3/Source/Model/FieldVariable.swift#L84)):*
<details><summary><i>Previously, vicng wrote…</i></summary><blockquote>

FieldVariable.isValidName(:) 
</blockquote></details>

Done.

---

*[Tests/Source/Model/FieldVariableTest.swift, line 23 at r3](https://reviewable.io:443/reviews/google/blockly-ios/271#-KXr9ZRgrLzkhx62R-ZY:-KXrF3urHseZOzjPOXCw:b-896fix) ([raw file](https://github.com/google/blockly-ios/blob/ec0d2364485e8143c6ad49f6ee998621fc45eca3/Tests/Source/Model/FieldVariableTest.swift#L23)):*
<details><summary><i>Previously, vicng wrote…</i></summary><blockquote>

Fix test method name
</blockquote></details>

Done.

---

*[Tests/Source/Model/FieldVariableTest.swift, line 30 at r3](https://reviewable.io:443/reviews/google/blockly-ios/271#-KXr9_sLZxQYDFRxgH2t:-KXrF4CMl90R9Nv7SDC9:b-896fix) ([raw file](https://github.com/google/blockly-ios/blob/ec0d2364485e8143c6ad49f6ee998621fc45eca3/Tests/Source/Model/FieldVariableTest.swift#L30)):*
<details><summary><i>Previously, vicng wrote…</i></summary><blockquote>

Here too
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/google/blockly-ios/271)*

**Pull request merged**
